### ISSUE TITLE
Add button to open config directory in finder from preferences window

### ISSUE THREAD

**Issue by krisak** [xor-gate/syncthing-macosx#10]
This might not concernt syncthing-macosx
I would like to change gui. For that i need $config_dir/gui.

It does not seem that its application support on osx - where config.xml is located.

How can i get to the right place please?

Again, sorry for spamming the issues.

**Comment by xor-gate** [comment]
```
Jerrys-MBP-405:~ jerry$ /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing -paths
```

**Comment by krisak** [comment]
Lovely. But i was at the right place so the problem is somewhere else. I dont think it needs to be possible to override from the gui (i asume you mean the tray->preferences). 

Thank you!

**Comment by xor-gate** [comment]
I would like to have a button to open finder in the gui override folder based on the configuration. This makes it much easier then navigating to the hidden folder.

**Comment by krisak** [comment]
It would be nice, but app works overall quite great actualy. I think only other thing i would like is the other issue with folder labels instead of IDs. 

Great work! THX

**Comment by xor-gate** [comment]
I started reworking the preferences dialog to have a toolbar. I had a major fight with Xcode/Objective-C and the GUI builder. But its working now (beta):

![progress example](https://media.giphy.com/media/l0HlztpJJic6ii9W0/giphy.gif)

**Comment by xor-gate** [comment]
As soon as I have added the "open config directory" button I will close this issue. Then still some work remains to make the window dynamic scale.

**Comment by krisak** [comment]
You should also somehow figure out how to put this somewhere more visible. Its best osx client for syncthing and it works well and its more up to date than the other one. Its just hard to find it.

**Comment by xor-gate** [comment]
Yeah I know, I have already added it to the documentation of syncthing and talked about it on the forum. When the new preferences window is ready I will tweet it is ready :+).

https://github.com/syncthing/docs/blob/d3a941dc634950cf174baf9025d4df7068e3e369/users/contrib.rst#os-x

**Comment by krisak** [comment]
Just detail - the other syncthing-bar has "(OSX 10.10 only)" the same aplies for syncthing-macosx. This can be also a bit misleading lot ofo the people would expect your client will work before 10.10 - lot of people still use older ones. Just detail

**Comment by xor-gate** [comment]
I know mine should support OS X since 10.8 or so, but not tested yet.

**Comment by krisak** [comment]
My coworker has 10.9 because he has older mac. Not working there. Might be OSX checking setup because he cant even run it (the app is grey). Clean syncthing binary works tho and you have the app in objective-c so i think it should work. We can test it but maybe you have to chceck something in xcod when you are bulding it?

**Comment by xor-gate** [comment]
The current releases are targeted at 10.10, but I have a current setup where 10.8 is targeted and compiles without problems.

**Comment by krisak** [comment]
That would be awesome.

**Comment by xor-gate** [comment]
I have pushed a new release (which is pinned still to 10.10). Have fun!
