### ISSUE TITLE
Brew cask formula does not work

### ISSUE THREAD

**Issue by uzzer** [xor-gate/syncthing-macosx#100]
Brew `caskroom` formula create in #23  is not updated and is not possible to install `syncthing-app` using homebrew `brew cask install syncthing-app`

It would not be so critical if we can `tap` from alternative cask source, while the formula from `fturcheti/syncthing-macos` is not updated.

The solution is to remove the line from Readme or fix the formula.

**Comment by calmh** [comment]
I removed the outdated instructions.

**Comment by xor-gate** [comment]
@calmh is pr #99 still relevant then ?

**Comment by calmh** [comment]
Maybe?

On 9 Apr 2019, at 19:28, Jerry Jacobs <notifications@github.com<mailto:notifications@github.com>> wrote:


@calmh<https://github.com/calmh> is pr #99<https://github.com/syncthing/syncthing-macos/pull/99> still relevant then ?

**Comment by calmh** [comment]
"brew cask install syncthing" does in fact install syncthing-macos. I’m not super happy about this doing something entirely different than "brew install syncthing", but there we are I guess.
