### ISSUE TITLE
Web interface: download progress of remote folders do not get updated

### ISSUE THREAD

**Issue by iwittkau** [xor-gate/syncthing-macosx#102]
macOS: 10.14.5 (18F132)
Syncthing: v1.1.4, macOS (64 bit)
Browsers:
- Safari: 12.1.1 (14607.2.6.1.1)
- Firefox: 67.0.3 (64-Bit)
- Chrome: 75.0.3770.100 (Official Build) (64-Bit)

Expected:
- Download progress of remote folders get updated automatically

Actual:
- Download progress of remote folders do not get updated and are stuck to size and percentage values of when the web interface was loaded.
- Local status like download/upload rate do get updated
- A `DownloadProgress` object is logged periodically in the browser's console
- No errors are logged in the browser or syncthing
- Same behavior on all browsers listed above
- Progress is displayed correctly when the users refreshed the web interface by reloading

**Comment by xor-gate** [comment]
Dear @iwittkau,

This project is about the application bundle/tray icon for macOS. If I
understand correctly there is an issue with the webinterface. This is part
of the syncthing/syncthing project. Please submit the bug report there.
Thanks in advance!

Kind regards,
Jerry

**Comment by iwittkau** [comment]
Ok, will do, thanks!
