### ISSUE TITLE
Included syncthing binary seems to be unable to update

### ISSUE THREAD

**Issue by Alexander-Serov** [xor-gate/syncthing-macosx#103]
This causes cross-platform cross-version compatibility issues. Terminal log:

> My-MacBook:syncthing user$ ./syncthing -version
> syncthing v0.14.6 "Dysprosium Dragonfly" (go1.7 darwin-amd64) jenkins@build.syncthing.net 2016-09-04 21:06:30 UTC
> My-MacBook:syncthing user$ ./syncthing -upgrade-check
> 15:55:21 FATAL: Upgrade: couldn't find a release to download

It shows a 2016 version, while the current version is that of June 2019. I have the latest version of `syncthing-bar` installed with `Homebrew`.

**Comment by calmh** [comment]
The current DMG bundles the 1.0.0 version which (while not super up to date now) does correctly auto upgrade. You have an old un-upgraded version in the custom location, possibly for legacy reasons. You can remove it.

**Comment by Alexander-Serov** [comment]
Sorry, I suppose I should be reporting it to the `syncthing-bar` project. Wrong repository! That's the executable that came with the package. I was confused since it is advertised on the main page of `syncthing`.

**Comment by Alexander-Serov** [comment]
Created an issue [here](https://github.com/m0ppers/syncthing-bar/issues/31).
