### ISSUE TITLE
MacOS app show Running (Offline) and issue with API

### ISSUE THREAD

**Issue by abrbon** [xor-gate/syncthing-macosx#104]
The app shows Running (Offline) when using the "Use HTTPS for GUI" setting.
The API key stays red when testing in de Syncthing Preferences. Both with using HTTPS of HTTP in de link. If you turn off HTTPS for GUI it seems to work fine but i do not want to use anything without HTTPS.

Also nothing shows in "Folders" when you look in the menu.

Tested on MacOS El Captitan v10.11.6 and the latest MacOS Cataline v10.15.1 and issues are on both.

**Comment by xor-gate** [comment]
Thanks @abrbon for reporting, it should have been fixed long time ago in #24 and commit https://github.com/calmh/syncthing-macos/commit/3a4a87162d102b4717f1fdd8525d770413c9106e by @calmh. Which is weird why it is not working, most people don't run syncthing webgui/api with a selfsigned certifcate. Its the best to terminate the http with an https reverse proxy (nginx, apache, haproxy, caddy). And let the webgui listen on 127.0.0.1 and public https only. That is the only workaround for now.

@calmh what do you think?

**Comment by abrbon** [comment]
You pointed me in the right direction! I solved it!
I had to add the self-signed cert to my Keychain, now it's working again with https :)

Stupid i didn't think of this myself :D
