### ISSUE TITLE
Hide icon

### ISSUE THREAD

**Issue by skhaz** [xor-gate/syncthing-macosx#108]
Is there a way to hide the syncthing icon from menu bar?

![photo_2020-03-30 11 15 10](https://user-images.githubusercontent.com/46259/77922728-cb8e5980-7277-11ea-95de-438bec383c48.jpeg)

**Comment by kenji21** [comment]
maybe you can use https://github.com/dwarvesf/hidden (or Bartender)

**Comment by xor-gate** [comment]
It could be possible to hide the icon, but where should it be visible then ?

**Comment by skhaz** [comment]
I ended using only the syncthing's binary.

**Comment by xor-gate** [comment]
You can indeed use it without the wrapper and run it under macOS launchctl.
