### ISSUE TITLE
support older versions of macOS

### ISSUE THREAD

**Issue by ec1oud** [xor-gate/syncthing-macosx#112]
10.9 was a good release: the last of the Steve Jobs-era design, and relatively efficient on older hardware.  Of course tray icons have existed for a long time.  I think it should not be too hard to make your current version compatible with macOS 10.9.

There's also some hardware for which 10.7 is the newest macOS release possible (such as the DVI Mac Mini).  It would be nice to support that too.  I still use one of those with VLC as a "home theater" machine.

**Comment by calmh** [comment]
For the record, the oldest macOS supported by current Syncthing is 10.10. It doesn't help much if this project supports much older OS:es than that.

**Comment by xor-gate** [comment]
As mentioned by @calmh we don't support old versions which are not supported by apple and golang toolchain.
