### ISSUE TITLE
Installation required `sudo` and GUI still shows yellow

### ISSUE THREAD

**Issue by p-i-** [xor-gate/syncthing-macosx#115]
I'm cross-linking the following post, as a project maintainer has indicated that the problem appears to be with the macOS integration rather than SyncThing core.

https://forum.syncthing.net/t/installation-required-sudo-on-macos-catalina-and-still-something-is-not-right/14925

I will link from that thread to this issue, I hope that's cleaner than duplicating content.

**Comment by imsodin** [comment]
I wrote nothing about opening an issue on github, i just pinged @xor-gate because he knows about the wrapper. The forum is still the appropriate place for support, let's keep it there until an actual big is identified.
