### ISSUE TITLE
Getting gzip: invalid header when trying to upgrade

### ISSUE THREAD

**Issue by dabeeeenster** [xor-gate/syncthing-macosx#118]
New laptop. Installed 1.0.0-2. Clicking on upgrade to 1.6.1 from the web app generates the error 

```
2020-06-03 12:37:38 Automatic upgrade (current "v1.0.0" < latest "v1.6.1")
2020-06-03 12:37:39 Automatic upgrade: gzip: invalid header
2020-06-03 12:37:42 upgrading: gzip: invalid header
```

**Comment by xor-gate** [comment]
This is because latest release bundles syncthing as zipfile and not as tarball anymore. Are you aware of this @calmh?

**Comment by calmh** [comment]
Yes. Syncthing 1.3.4+ can upgrade using zip archives.

**Comment by dabeeeenster** [comment]
I didnt spend long looking for a newer binary but couldn't find one?

**Comment by xor-gate** [comment]
I'm currently trying to release v1.6.1 but there are some issue with installation

**Comment by xor-gate** [comment]
@dabeeeenster could you try latest release https://github.com/syncthing/syncthing-macos/releases/tag/v1.6.1-1?

**Comment by dabeeeenster** [comment]
This looks like its still running the 1.0.0 daemon. 

Still getting messages: `gzip: invalid header` and if I run about in the web app I see v1.0.0

**Comment by xor-gate** [comment]
- Stop syncthing
- Open Terminal.app
- Execute `rm -Rf ~/Library/Application\ Support/Syncthing-macOS`
- Start syncthing

**Comment by dabeeeenster** [comment]
Ah yep that worked - thanks so much!

**Comment by xor-gate** [comment]
It will be fixed in a next release, the problem is the syncthing bundle copies the daemon into a place where it can be auto-updated. But the auto-update will be disabled in the future and only will run with the bundled syncthing daemon executable.

**Comment by unfriend** [comment]
Hi, i just installed the https://github.com/syncthing/syncthing-macos/releases/tag/v1.6.1-1 and deleted the folder and i still get the error :(

**Comment by xor-gate** [comment]
You must make sure syncthing is stopped, then directory removed and then started again. I have no clue why @unfriend problems still persists because it works for @dabeeeenster.

**Comment by unfriend** [comment]
@xor-gate stopping and quitting then deleting and restarting fixed it, thanks for the great work!
