### ISSUE TITLE
Versions in app are out of sync with versions in feed again

### ISSUE THREAD

**Issue by vitorgalvao** [xor-gate/syncthing-macosx#120]
Seems like a repeat of https://github.com/syncthing/syncthing-macos/issues/90.

* `106010001` is in CFBundleVersion (app).
* `100600101` is in sparkle:version (feed).
* `1.6.1-1` is in CFBundleShortVersionString (app).
* `v1.6.1-1` is in sparkle:shortVersionString (feed).

**Comment by xor-gate** [comment]
Oops, thanks for the report will fix it with 1.7.0
