### ISSUE TITLE
No start at login and "Running (Offline)"

### ISSUE THREAD

**Issue by khinsen** [xor-gate/syncthing-macosx#121]
Yesterday I installed the latest Syncthing (1.6.1-1) on a brand new MacBook running Catalina (10.15.5). It shows two problems to which I haven't found any solution so far:

 - Even though I have "start at login" checked off, it doesn't start at login. I have to launch it manually every time.

 - I have all the symptoms described [here](https://github.com/syncthing/syncthing-macos/issues/104): the status in the menubar is shown as "Running (Offline)", in the submenu the "API" entry is red, and under "Preferences" the "Test" button is red as well. However, contrary to that old (and closed) issue, I have *not* chosen HTTPS for the GUI.

In spite of the "offline" status, Syncthing seems to work just fine. And when I run the syncthing executable directly from the terminal, I get no error message at all.

Does anyone have suggestions for debugging this?

**Comment by xor-gate** [comment]
How do you run syncthing from the terminal like: `/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing`?

**Comment by khinsen** [comment]
No, I mean running just the non-GUI executable: `~/Library/Application\ Support/Syncthing-macOS/syncthing`. This shows no sign of a problem.

**Comment by xor-gate** [comment]
Could you try to upgrade to latest release https://github.com/syncthing/syncthing-macos/releases/tag/v1.7.0-1

**Comment by khinsen** [comment]
No change, sorry!

**Comment by xor-gate** [comment]
Could you open the webinterface at http://127.0.0.1:8384/ and copy the api key from Actions -> Advanced -> Api key to the Syncthing -> preferences -> API key and try to use the test button. It is also possible you have a username and password set on the gui ?

**Comment by gamebox** [comment]
I'm having a similar issue, but on macOS Big Sur (trying to find issues on a secondary device), and completed the steps above.  When I press the test button, it goes green, but I still have the same status.  There is no other indication about the test result.

**Comment by khinsen** [comment]
@xor-gate I am currently travelling, without the machine that shows the problem, so I won't be able to test before August, sorry.

**Comment by tokred** [comment]
Had the same issue (macOS 10.15.5 / syncthing 1.7.0-1) and in fact the API key was wrong in the Preferences window.

After copy-paste form the web interface, the Test button worked and turned green. However, the new key did not survive Syncthing restart as it was not properly saved. I entered the API key again and then hit Enter in API key field and changed also the focus to the URI field (to somehow save it, there is no dedicate Save button). Seemed to work now, still holds after restart and the icon shows "Online".

Regards

**Comment by samrenfrew** [comment]
I have the same issue, with my Syncthing freezing and not responding after opening. I have a distinct feeling its related to the fact that I changed the default setting from using localhost/127.0.0.1 to an internal IP address - I'm now on a different wifi, with a different IP address, so Syncthing is unable to start on the assigned IP address. Annoyingly there's no way for me to change it in preferences as it's crashing on startup

**Comment by xor-gate** [comment]
You need to edit the xml file manually when you broke the config. Its located at `~/Library/Application Support/Syncthing/config.xml`

**Comment by khinsen** [comment]
@xor-gate Back home! I followed the instructions given above by @tokred, and that fixed the problem for me as well.

**Comment by xor-gate** [comment]
I will create a FAQ and drop the manual necessary workaround when it occurs in there. Thanks for the feedback.
