### ISSUE TITLE
push release 1.8.0 to github?

### ISSUE THREAD

**Issue by dmd** [xor-gate/syncthing-macosx#123]
Why is the latest version at https://syncthing.net/downloads/ 1.8.0, but the latest release on https://github.com/syncthing/syncthing-macos/releases 1.7.0?

**Comment by xor-gate** [comment]
Good question, syncthing and syncthing-macos projects are separate and the syncthing-macos bundle needs manual updating. So it will lag behind at maximum a few weeks.
