### ISSUE TITLE
Upgrade to 1.8 on MacOS breaks certain static IP connections

### ISSUE THREAD

**Issue by devren-y** [xor-gate/syncthing-macosx#125]
Syncthing had been working perfectly on my Mac for months, since I installed it (version 1.6 or 1.7), synced to four other devices on my office network.  Then, a few weeks ago, it auto-upgraded to version 1.8, and immediately two of the four devices could no longer communicate.

I tried many things (restart, pause/unpause, delete/re-add, uninstall/reinstall) and the same two connections would never work.   Finally, I used Homebrew to downgrade Syncthing on the Mac, since version 1.7 was still available — and immediately it worked perfectly again.   Then, today I decided to try upgrading it to 1.8 again.  Exactly the same problem happened again.  This time I wiped and rebuilt the configuration from scratch, but the same two connections would not work.  Finally I downgraded again by getting the 1.7 binary from Github, and now it works perfectly again, no reconfiguration needed.  (Except there is an exclamation mark on my icon which falsely reads "Running (Offline)".)

Neither the Mac nor any of the other four devices is running global discovery, relays or NAT traversal.  The devices are all on different subnets. tunneled through various VPNs, but they all (except the Mac) have static IPs.  So, when pairing a device with the Mac, I would go to the "Advanced" tab and type `tcp://[static IP]`.  Again, this worked perfectly on version 1.7 and below.  The Mac would initiate the connections and establish the TCP sessions with each peer device.  Also, I can ping and reach all the web GUIs perfectly fine at those IP addresses.  None of them are running non-standard ports.

The various peer devices are running various versions of Syncthing (1.4, 1.6, 1.8), mostly on Linux, some in Docker containers.  Of the two Syncthing 1.4s in Docker containers, one could connect to the Mac and one could not.  The Linux devices that I have updated to 1.8 have no problems like this Mac, and we also have Windows devices that updated to 1.8 that likewise have no problems.

When watching the log messages on the Mac, there seemed to be no traffic to or from the disconnected devices.  The Device ID and static IP are announced when Syncthing starts up, and eventually a red message appears in the web GUI, "i/o timeout reached."   That is all the evidence I could find.

What is different in 1.8 that might cause this to break?  Thank you very much for your help!

**Comment by calmh** [comment]
Sounds like https://github.com/syncthing/syncthing/issues/6892

**Comment by xor-gate** [comment]
Should be fixed in https://github.com/syncthing/syncthing/releases/tag/v1.9.0 under syncthing/syncthing#6892: Syncthing 1.8.0 trying to connect via wrong network route. A new v1.9.0 macos bundle is released.

**Comment by devren-y** [comment]
Great, thank you all very much!
