### ISSUE TITLE
1.9.0?

### ISSUE THREAD

**Issue by anamba** [xor-gate/syncthing-macosx#126]
I have a situation that is probably unusual, but still, I thought I'd document it here in case someone else ends up in a similar situation.

I discovered today that one of my computers was still running the older version (1.6?) that (1) didn't auto-update and (2) did not set `STNOUPGRADE=true`. The service would not start, so first I tried updating to the latest release of syncthing-macos here, which is 1.8.0. However, that didn't work either.

I tried running the syncthing executable from the app bundle directly to see the actual error message, which indicated that the config and db were too new, so it seems it had been running syncthing 1.9 (I couldn't confirm this because the latest syncthing-macos deleted the syncthing executable).

I downloaded 1.9 from syncthing/syncthing and ran it just long enough to determine that it worked with my config and db. Following that, I didn't think this was still an ok thing to do, but I tried replacing the executable within the app bundle and ... it worked!

It would be nice to have an official 1.9.0 release, but this workaround will do for now. Ok to close this issue.

**Comment by xor-gate** [comment]
Thanks for reporting, I broke the auto-updater (again) so indeed the shipped syncthing auto-update itself. With the new bundle it is locked to its version with STNOUPGRADE=true. I have planned this weekend to create a new 1.9.0 release.

**Comment by xor-gate** [comment]
Fixed in https://github.com/syncthing/syncthing-macos/releases/tag/v1.9.0-1
