### ISSUE TITLE
Automatic upgrade on one machine, not another

### ISSUE THREAD

**Issue by jeremycherfas** [xor-gate/syncthing-macosx#129]
I have syncthing-macos on an iMac and a Macbook air. Both machines run OS 10.13.6

I noticed to day that the MBA has version 1.10.0 with automatic upgrades enabled for stable releases. The iMac has version 1.9.0 with automatic upgrades "Unavailable/Disabled by administrator or maintainer".

I read the issue [Automatic upgrades in GUI](https://github.com/syncthing/syncthing-macos/issues/122), which suggests to me that there will be a lag of a few weeks. 

I don't quite understand why the MBA has 1.10.0 -- which seems not to have been released yet -- while the iMac, with the same OS, has 1.9.0

Of course, if this is nothing to worry about, I will just accept it as it is and stop worrying.

Thanks

**Comment by xor-gate** [comment]
You should check which syncthing-macos version you are running, the Macbook air runs probably v1.7.0 bundle where auto-upgrade of the syncthing daemon is enabled. You can check the version by clicking the tray icon -> about -> look at the version. The version after it had a manual typo which results in the bundle not being updated. The iMac then probably runs a newer bundle where the auto-upgrade of the daemon is disabled but will be shipped periodically with the bundle. You should update manually the macbook to the latest version and then you get the latest bundle. Within a few days I will hopefully create a v1.10.0 bundle.

Please let me know if this fixes the issue.

**Comment by xor-gate** [comment]
Latest release has been [bundled (v1.10.0-1)](https://github.com/syncthing/syncthing-macos/releases/tag/v1.10.0-1)

**Comment by jeremycherfas** [comment]
Thank you. Fixed.
