### ISSUE TITLE
Tray icon no longer appears

### ISSUE THREAD

**Issue by ddickstein** [xor-gate/syncthing-macosx#131]
I recently upgraded syncthing to v1.10.0, installed via `brew install syncthing` (previous version was I think 1.07 from a cask). The tray icon for syncthing is gone. Syncthing is definitely still running, and the web UI is available. How can I restore the tray icon?

Mac OS: 10.15.7 (19H2)

**Comment by xor-gate** [comment]
This is weird, have you tried uninstalling and installing again? There is no code which hides the tray icon, it's the main purpose of the application.

**Comment by xor-gate** [comment]
Probably you have installed syncthing daemon with homebrew and syncthing-macos needs to be installed by hand or by using homebrew cask `brew cask install syncthing`. I think it is uninstalled.

[README.md](https://github.com/syncthing/syncthing-macos#installation)
> The latest version is available at Github Releases, or it can also be installed using homebrew `brew cask install syncthing`

**Comment by ddickstein** [comment]
Yes you're right. Thank you! Separately, the status says "Unknown (Online)" and it says "Syncthing Service (Stopped)" but start doesn't seem to have an effect. Maybe the service is immediately crashing after starting up.

In Console.app I see the following lines looped:

```
default	08:50:19.478907-0400	Syncthing	Launching Syncthing daemon
default	08:50:19.480350-0400	Syncthing	Launching Syncthing daemon
default	08:50:19.558636-0400	Syncthing	Syncthing daemon terminated (exit code 1)
default	08:50:19.558718-0400	Syncthing	Delaying daemon startup by 10.0 s
default	08:50:19.558793-0400	Syncthing	Syncthing daemon terminated (exit code 1)
default	08:50:19.558837-0400	Syncthing	Delaying daemon startup by 10.0 s
default	08:50:21.660710-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> resuming, QOS(0x21) Voucher (null)
default	08:50:21.661839-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> now using Connection 37
default	08:50:21.662081-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> sent request, body N 0
default	08:50:21.662615-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> received response, status 200 content K
default	08:50:21.662710-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> response ended
default	08:50:21.662755-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> done using Connection 37
default	08:50:21.662841-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> summary for task success {transaction_duration_ms=1, response_status=200, connection=37, reused=1, request_start_ms=0, request_duration_ms=0, response_start_ms=1, response_duration_ms=0, request_bytes=270, response_bytes=486, cache_hit=0}
default	08:50:21.662947-0400	Syncthing	Task <47A7D1C1-8E03-4290-B511-BBE1F28BC11B>.<86> finished successfully
default	08:50:26.659789-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> resuming, QOS(0x21) Voucher (null)
default	08:50:26.660974-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> now using Connection 37
default	08:50:26.661318-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> sent request, body N 0
default	08:50:26.661725-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> received response, status 200 content K
default	08:50:26.661839-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> response ended
default	08:50:26.661902-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> done using Connection 37
default	08:50:26.661995-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> summary for task success {transaction_duration_ms=1, response_status=200, connection=37, reused=1, request_start_ms=0, request_duration_ms=0, response_start_ms=1, response_duration_ms=0, request_bytes=270, response_bytes=486, cache_hit=0}
default	08:50:26.662096-0400	Syncthing	Task <2E4B3AF0-1375-436E-AA4D-CFE7C8FA8BB9>.<87> finished successfully
```

The web UI seems to work and report that everything is up to date. Is this something I need to worry about? Do you know what might be going wrong here or what the impact of the service being reported down is?

**Comment by xor-gate** [comment]
You must uninstall syncthing daemon which is installed with `brew install syncthing` . Homebrew .app installation uses the cask which is installed with `brew cask install syncthing` which installs the bundle. The bundle is unable to run the syncthing daemon because you run it from homebrew. Just use `brew uninstall syncthing`.
