### ISSUE TITLE
Version 1.10.0-1 rejected by GateKeeper in Catalina and Big Sur

### ISSUE THREAD

**Issue by Keeblo** [xor-gate/syncthing-macosx#133]
The executable in the 1.10.0-1 DMG is rejected by GateKeeper in Catalina and Big Sur.

Version 1.9.0-1 *is* accepted by GateKeeper in Big Sur, so perhaps something went wrong in the signing process?

Thank you for your hard work bringing Syncthing to macOS! :-)

**Comment by xor-gate** [comment]
I'm trying to release a new 1.11.1-1 version which will hopefully fix this.

**Comment by xor-gate** [comment]
Could you test https://github.com/syncthing/syncthing-macos/releases/tag/v1.11.1-1 ?

**Comment by Keeblo** [comment]
Worked flawlessly!

A dozen thanks and a thousand Internet points to you, xor-gate!

**Comment by xor-gate** [comment]
Thanks for testing!
