### ISSUE TITLE
syncthing-macos doesn't work on Apple Silicon ARM M1 processor

### ISSUE THREAD

**Issue by creedda** [xor-gate/syncthing-macosx#135]
Wanted to report that although SyncThing runs using rosetta 2 on an M1 Macbook Air, it does seem to crash after a bit.

Any logs I can send in to help troubleshoot or any chance of a release compiled for apple silicon?

Just wanted to report in.

Macos 11.0.1
M1 Macbook Air
syncthing-macos v1.10.0, macOS (64 bit)
"Fermium Flea"
Build 2020-09-15

If you can let me know where the log files get stored by default I can upload a sanitized version.

Thanks!

**Comment by xor-gate** [comment]
Syncthing is compiled with the [golang.org](https://golang.org) toolchain and Darwin (macOS) on ARM is not supported yet. The syncthing-macos is just a wrapper for syncthing and should be easily to recompile for ARM, but supporting two builds is not so easy with the current auto-updater.

**Comment by xor-gate** [comment]
See also https://github.com/syncthing/syncthing/issues/7128

**Comment by creedda** [comment]
Wanted to comment that over the last week or so I haven't seen any crashes. Might have just been some initial rossetta 2 issues but everything seems to be working fine now.

Let me know if I can help with testing for a universal version. Will check the other issue.

**Comment by xor-gate** [comment]
This issue is related to #137
