### ISSUE TITLE
auto updates are broken again - infinite update loop

### ISSUE THREAD

**Issue by core-code** [xor-gate/syncthing-macosx#136]
just like back in https://github.com/syncthing/syncthing-macos/issues/90

the bundle version in the feed is
101100101

the bundle version in the app is
101100001

this is not identical

=>

even the very newest version will still ask to be updated but will just re-install the very same version again 

<img width="732" alt="Screenshot 2020-11-21 at 11 55 48" src="https://user-images.githubusercontent.com/1261954/99875519-b2645f80-2bf0-11eb-8e41-694c871f09a1.png">

**Comment by xor-gate** [comment]
Fixed in https://github.com/syncthing/syncthing-macos/commit/04d82f93605f211a4871b5b84bd4650aea81109a

**Comment by core-code** [comment]
thanks i can confirm it is resolved

**Comment by xor-gate** [comment]
Sorry for the inconvenience 😄

**Comment by core-code** [comment]
no problem there :-)
