### ISSUE TITLE
Seems not working on macOS Big Sur

### ISSUE THREAD

**Issue by Latlantis** [xor-gate/syncthing-macosx#137]
Hi,
i'd like just to share my experience since it seems that the **Syncthing.app** is not working anymore with the last mac version.
If you tell me where I can found some logs if any I'll be attach them to the issue for troubleshooting purpose.
Thank you for your work.

**Comment by xor-gate** [comment]
Can you be a little more specific? E.g:
- Which syncthing-macos version
- What do you see?

I have not tested yet on macOS big sur myself.

**Comment by Latlantis** [comment]
Hi,
the version of syncthing-macos is I guess the last stable one: Syncthing-1.11.1-1
When I click on the icon, I see absolutely nothing, no jumping app icon, no errors, no crash even no process in Activity Monitor just refuse to launch. 
Unfortunately I'm not able to give you more details. Thank you

**Comment by kbn** [comment]
Syncthing 1.11.1 works without issues here, macOS Big Sur fresh install on M1 MBPro.

**Comment by sirn** [comment]
I saw similar symptoms as @Latlantis', but later found out this was due to firewall in macOS settings (I didn't get the allow/deny dialog when I launched Syncthing, mine was M1 Mac so maybe Rosetta 2 bug?) Syncthing works perfectly once I add the application bundle to the firewall exception list and relaunch the app.

**Comment by fredoliveira** [comment]
I wanted to see if I could update the code for `syncthing-macos` to build an apple silicon binary and did so at [fredoliveira/syncthing-macos](fredoliveira/syncthing-macos) ([comparison view](https://github.com/syncthing/syncthing-macos/compare/develop...fredoliveira:develop)). In short, I did the following: 

- Changed the bundle script to grab the `arm64` build of `syncthing` (1.12-rc.1)
- Updated `VALID_ARCHS` to include arm64
- Upgraded Sparkle to the [latest release](https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0) (which supports universal binaries)

After a couple of tweaks, it worked. I assume you folks don't necessarily want to create a release while a final 1.12.1 is out, but for folks who may want a M1-ready binary and aren't afraid to bundle a release candidate of `syncthing`, a `make release` in my repo will build one in a few seconds. With a M1-ready `syncthing` binary running in a M1-ready wrapper, everything runs normally, with no crashes.

@xor-gate I'm more than happy to open a PR, but this is such an insignificant change that you folks can just replicate my efforts in a few minutes. The tricky part is going to be grabbing (and then running) the correct `syncthing` binary depending on which architecture the user is running on. The script that does that may require some significant refactoring.

**Comment by xor-gate** [comment]
Hi @fredoliveira thanks for the work, with your change it is currently only possible to run arm64 syncthing daemon. I prefer to ship both x86_64 and arm64 binaries for syncthing and auto-select them during startup. For my own reference: we need to use the [uname system call, machine property](https://pubs.opengroup.org/onlinepubs/7908799/xsh/sysutsname.h.html) from swift as described on the [apple forum](https://developer.apple.com/forums/thread/652667?answerId=624824022#624824022).

**Comment by xor-gate** [comment]
@Latlantis I have upgraded one system with Big Sur and i'm running syncthing without any issue. Maybe you could try to use the Applications -> Utilities -> Console application and see if there any Syncthing Crash Reports.

**Comment by roopkeed** [comment]
I have changed the default port and syncthing started to don't start.
I fix it with reboot my macbook air M1
