### ISSUE TITLE
Bundle universal binary for intel and Apple M1 (arm) CPU

### ISSUE THREAD

**Issue by xor-gate** [xor-gate/syncthing-macosx#138]
I wanted to see if I could update the code for `syncthing-macos` to build an apple silicon binary and did so at [fredoliveira/syncthing-macos](fredoliveira/syncthing-macos) ([comparison view](https://github.com/syncthing/syncthing-macos/compare/develop...fredoliveira:develop)). In short, I did the following: 

- Changed the bundle script to grab the `arm64` build of `syncthing` (1.12-rc.1)
- Updated `VALID_ARCHS` to include arm64
- Upgraded Sparkle to the [latest release](https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0) (which supports universal binaries)

After a couple of tweaks, it worked. I assume you folks don't necessarily want to create a release while a final 1.12.1 is out, but for folks who may want a M1-ready binary and aren't afraid to bundle a release candidate of `syncthing`, a `make release` in my repo will build one in a few seconds. With a M1-ready `syncthing` binary running in a M1-ready wrapper, everything runs normally, with no crashes.

@xor-gate I'm more than happy to open a PR, but this is such an insignificant change that you folks can just replicate my efforts in a few minutes. The tricky part is going to be grabbing (and then running) the correct `syncthing` binary depending on which architecture the user is running on. The script that does that may require some significant refactoring.

_Originally posted by @fredoliveira in https://github.com/syncthing/syncthing-macos/issues/137#issuecomment-753409287_

**Comment by xor-gate** [comment]
Hi @fredoliveira thanks for the work, with your change it is currently only possible to run arm64 syncthing daemon. I prefer to ship both x86_64 and arm64 binaries for syncthing and auto-select them during startup. For my own reference: we need to use the [uname system call, machine property](https://pubs.opengroup.org/onlinepubs/7908799/xsh/sysutsname.h.html) from swift as described on the [apple forum](https://developer.apple.com/forums/thread/652667).

**Comment by fredoliveira** [comment]
@xor-gate correct, yup. And I agree that it would be preferable to have a single universal package for distribution. The problem with building a universal binary is that you need to include 2 separate `syncthing` binaries inside the bundle which may make things a little larger than necessary (even if, let's be honest, the `syncthing` binary is pretty small). 

Should be relatively easy to build something that grabs both `syncthing` binaries on build, and when the wrapper runs, it just picks the correct one for the running architecture.

**Comment by FiloSottile** [comment]
You can also use the `lipo` tool to generate a universal binary, and macOS will take care of running the version that's appropriate for the system.

**Comment by xor-gate** [comment]
Thanks for the tip @FiloSottile

**Comment by xor-gate** [comment]
@fredoliveira we can only continue on this when Golang 1.16 is release with proper M1 support and Syncthing is build with it. It seems latest v1.12.1 release doesn't include the arm64 build anymore. @calmh you will add arm64 official support when the 1.16 toolchain is out or what is your planning?

**Comment by calmh** [comment]
1.13.0-rc.1 is available as universal, and I intend to release that as 1.13.0 with the Go 1.16 beta. It seems to work fine for me, albeit without quic support. I didn't release 1.12.1 as the build story wasn't really in place around quic and whatnot. (If/when Syncthing auto upgrades it will be to a thinned version for the current architecture but that's fine I think.)

**Comment by xor-gate** [comment]
The build was not yet uploaded to github releases when I found out 1.13.0-rc.1 was out, indeed there is a universal now. Then we will wait for v1.13.0 to be release then. Thanks @calmh

**Comment by xor-gate** [comment]
How is the universal binary build, i'm unable to find any reference to 'universal' or 'lipo' in the main repo?

**Comment by calmh** [comment]
Yeah, some build stuff lives on the build server. It's a normal amd64 build and a normal arm64 build glommed together with lipo. In practice:

```
unzip ../syncthing-macos-amd64-*.zip
unzip ../syncthing-macos-arm64-*.zip
lipo -create syncthing-macos-amd64-*/syncthing syncthing-macos-arm64-*/syncthing -o syncthing
```

and then zip it up

**Comment by fredoliveira** [comment]
Oh, those are great news then. Because there's effectively a universal version of the `syncthing` binary, the `syncthing-resource.sh` script can largely be the same as it is right now, and the existing make process (with [my changes](https://github.com/fredoliveira/syncthing-macos), at least) will build a fully Universal version of syncthing-macos. 

Locally (on top of my previous changes), I changed `syncthing-resource.sh` to read:

```bash
SYNCTHING_ARCH="universal"
SYNCTHING_VERSION="1.13.0-rc.1"
```

And a `make release-dmg` created a universal binary version of `syncthing-macos` that packs the universal binary version of the `syncthing` binary too. This is great!

**Comment by FiloSottile** [comment]
Do you think it would be possible to make a 1.13.0-rc.1 version of syncthing-macos, to test the universal build?

**Comment by fredoliveira** [comment]
> Do you think it would be possible to make a 1.13.0-rc.1 version of syncthing-macos, to test the universal build?

If you pull [my fork](https://github.com/syncthing/syncthing-macos/compare/develop...fredoliveira:develop) and `make release-dmg`, it will build exactly that, but you may also want to wait for @xor-gate to build one here and tag it. I've been my build since yesterday and it works as expected. 

@xor-gate any plans to officially support release candidates too, or is your philosophy to only do majors and minors?

**Comment by xor-gate** [comment]
Hi @fredoliveira, i have no plans to support release candidates. But for now you can open a PR against branch issue-138, then the https://build.syncthing.net will run and we can test if the dmg works.

**Comment by fredoliveira** [comment]
> Hi @fredoliveira, i have no plans to support release candidates.

Makes sense, I totally understand that. I also feel like in general there's no need for it - it's just that this once, it is interesting for folks on M1-based macs to have a M1-ready build as soon as possible.

> But for now you can open a PR against branch issue-138, then the https://build.syncthing.net will run and we can test if the dmg works.

Just did that :-) Let's see how that goes!

Edit: looks like it built successfully. I grabbed the [resulting artifact from teamcity](https://build.syncthing.net/viewLog.html?buildId=91010&buildTypeId=SyncthingMacOS_BuildReleaseDmg&tab=artifacts) and it looks good!

**Comment by mstansberry** [comment]
#144 merged to hopefully resolve this issue

**Comment by xor-gate** [comment]
New [v1.13.0](https://github.com/syncthing/syncthing-macos/releases/tag/v1.13.0-1) release created, test and have fun people.

**Comment by fredoliveira** [comment]
Already running here. Thank you for your work!

**Comment by xor-gate** [comment]
Thank you also @fredoliveira !
