### ISSUE TITLE
Option to don't show menu bar icon on macOS

### ISSUE THREAD

**Issue by Vinz87** [xor-gate/syncthing-macosx#143]
I'm using the macOS application bundle, and I would like to hide the menu bar icon: is this currently possible? Or can it be addressed in a future release?
Thank you

**Comment by xor-gate** [comment]
The whole purpose of syncthing-macos is to have an application wrapper and have it visible somewhere. If you want to hide the application you are better of using only the daemon and launchctl. See https://docs.syncthing.net/users/autostart.html#macos.

**Comment by Vinz87** [comment]
> The whole purpose of syncthing-macos is to have an application wrapper and have it visible somewhere. If you want to hide the application you are better of using only the daemon and launchctl. See https://docs.syncthing.net/users/autostart.html#macos.

let me disagree :) the purpose of having syncthing as an application is precisely to let users installing and using it without having to tweak around with terminal, installing homebrew, etc. etc.
Moreover, since the real Syncthing's GUI is the web page hosted locally, there is no true need of having it "visible somewhere". I still open it by going to Syncthing's ip:port address. It can be nice for someone to have it as a menu icon, it can be otherwise for others, simply a personal taste. That's the whole purpose of an app preferences pane.

**Comment by xor-gate** [comment]
You convince me which basically means imho:

- We should be able to hide-onhide the menu bar icon
- We should be able  to have an icon in the dock or from the application folder to be openened which then opens the preferences pane to control the menu bar icon

Is this what you suggests as a new feature?

**Comment by imsodin** [comment]
Isn't this a feature request for macos? Every desktop I know (prob. not representative, but: Windows, Xfce, KDE) lets you configure which icons should be shown or hidden. Doing it the other way round seems incredibly wasteful: It means every software that runs a daemon needs to implement some logic, UI, ... to configure whether it's icon should be shown.

**Comment by vincentardern** [comment]
Yup it's ridiculous, but that's macOS for you. Bartender is paid software that lets you intelligently hide icons. Why do you have to pay to get that feature?? Who knows.... Anyway, some of us will continue to use Macs despite these oddities because the other software is so good

**Comment by Vinz87** [comment]
> You convince me which basically means imho:
> 
> * We should be able to hide-onhide the menu bar icon
> * We should be able  to have an icon in the dock or from the application folder to be openened which then opens the preferences pane to control the menu bar icon
> 
> Is this what you suggests as a new feature?

Syncthing has always been an invisible background process for me, when I needed it I just opened the web interface from the browser (still the only Syncthing available GUI).

I simply would like to stay like this and, as other macOS apps let the user to do, to be able to select an option to hide the menubar icon.

**Comment by Vinz87** [comment]
@imsodin @vincentardern every macOS app that I use has some sort of option for customizing appearance. Some let the user hide or show the menubar icon, other even the dock icon.

**Comment by imsodin** [comment]
I think the arguments are clear here. I didn't intend to say syncthing-macos should not have that option. I am just voicing my support for a potential decision to declare this as out-of-scope (or just too low prio/benefit to implement). In the end it's up to @xor-gate (or potential other contributors).

**Comment by jakob** [comment]
I took a shot at implementing this feature in PR #169!

I added a checkbox for hiding the menu bar icon to the preferences, and you can even just cmd-drag the icon to remove it.

Here's the link to download a build of that PR: https://build.syncthing.net/repository/download/SyncthingMacOS_BuildReleaseDmg/113806:id/Syncthing-1.18.4-1.dmg

What do you guys think?

**Comment by xor-gate** [comment]
Thanks @jakob for your effort it looks good to me.

**Comment by jakob** [comment]
Are you planning to merge my PR, or are you waiting for more feedback? I totally understand if you are busy, I'm just wondering if there's anything I can do to make it easier to review the change and/or decide whether the new feature is a good fit for Syncthing-macOS.

Obviously being able to hide the icon is not 100% necessary, so this feature isn't high priority. But in my experience there is a group of Mac users that really wants to keep their menu bar clean. For example, being able to hide the menu bar icon was also a recurring feature request for Postgres.app from users until we added a checkbox.

**Comment by xor-gate** [comment]
Hi there @jakob, didn't you get notified of review comments in the PR? I had a few remarks, and I appreciate your effort and would like to integrate this feature for the (probably) minority people wanting this. Have a look in the PR for the review comments and we can proceed there! Thanks for poking me, but actually I was waiting for you to process the comments.

**Comment by jakob** [comment]
@xor-gate I don't see any comments. Here's what the PR looks like in my browser:
<img width="818" alt="Bildschirmfoto 2021-12-18 um 10 26 56" src="https://user-images.githubusercontent.com/198305/146636323-041b84e5-8a91-4bd2-962c-cb1c7fb2fc61.png">

**Comment by xor-gate** [comment]
Hi @jakob, I would like to say I was not aware the new github review system (not using is very much) has a state "Pending" and the review was not be submitted. Hopefully now you got a mail and see the review comments. Thanks!

**Comment by jakob** [comment]
I think this issue can be closed!

**Comment by xor-gate** [comment]
You are right @jakob thanks! This feature was part of [v1.18.5-2](https://github.com/syncthing/syncthing-macos/releases/tag/v1.18.5-2) release.

**Comment by Vinz87** [comment]
Thank you!
