### ISSUE TITLE
Preferences dialog is not clear

### ISSUE THREAD

**Issue by daveteu** [xor-gate/syncthing-macosx#149]
### Include required information

My first attempt creating Syncthing, first on my ubuntu servers, then tried to sync file on my macOS. I was going over the docs trying to install an "instance" on my macos only to realise the macOS app also installed a local instance.

What more confusing, is the "Preference" settings, I feel it's very much better naming it as "Connect to", with the option of Local (the instance installed with the app), or an option to connect to a remote server + API Key. ( because, till now, I don't really know what this preference do)

Thanks for the great tool, it's fast and easy to work with!

**Comment by xor-gate** [comment]
Currently the application is not able to handle remote instances properly so it will only use the locally bundled instance. It is automatically filled in so you should probably know what you are doing when changing any of this. I will add a note in the FAQ.
