### ISSUE TITLE
Advanced preferences - Syncthing-inotify executable

### ISSUE THREAD

**Issue by xor-gate** [xor-gate/syncthing-macosx#15]
We should add and enable the syncthing-inotify executable which is the same as #14.
- Enable / disable inotify
- Selectable custom inotify
- Start / stop inotify

**Comment by cowai** [comment]
This would be a very nice feature.

**Comment by dodekeract** [comment]
Any news on this?

**Comment by xor-gate** [comment]
I didn't spend any time yet on this feature yet

**Comment by xor-gate** [comment]
Probably the inotify feature will be part of the syncthing executable see this PRs (last activity 3 days ago):
https://github.com/syncthing/syncthing/pull/3986

**Comment by dodekeract** [comment]
That's awesome. Now the only thing Syncthing needs to add is untrusted servers (store files unencrypted locally, encrypt before sending, verify upon receiving, prevent untrusted changes). 😉

**Comment by xor-gate** [comment]
Thats a different story, and has nothing todo with the syncthing-macosx project. Untrusted servers will never happen as this is the core design of syncthing.

**Comment by dodekeract** [comment]
@xor-gate I'm aware that it isn't related to this project. I'm just sharing my general enthusiasm about the direction syncthing is headed. Including `inotify` in the core is a big step in the right direction and will make the project a lot more user-friendly.

That being said, why do you think untrusted servers aren't possible/likely for syncthing? It really sucks that I have to add a layer of userspace crypto (Cryptomator, has to be mounted via WebDAV...) on my local system before being able to securely sync stuff to my dedicated root server.

**Comment by xor-gate** [comment]
Please keep things on topic and not chatting in an issue. Please use the [chat then](https://gitter.im/syncthing-macosx/Lobby).

**Comment by xor-gate** [comment]
This executable is not needed anymore as since per [v0.14.40](https://github.com/syncthing/syncthing/releases/tag/v0.14.40) it is part of the main executable, only needs to manually enabled.
