### ISSUE TITLE
macOS version numbers

### ISSUE THREAD

**Issue by tohvanah** [xor-gate/syncthing-macosx#150]
My apologies if this is out of place, or should be clear to me... Why are strange macOS version numbers used in this project? In release notes it references "macOS 11.11" and "macOS 11.12", and in the readme FAQ section it references "macOS 1.11" and "macOS 1.12", none of these four versions of macOS exist. 

I started noticing when a Sparkle update came across today referencing "macOS 11.11" now required for release v1.14.0-1; I panicked that only Big Sur would now be supported!

**Comment by xor-gate** [comment]
You are very right, i must have been sleeping while writing about the macOS version numbers I have now corrected it. Thanks for the report and my bad !
