### ISSUE TITLE
Tray icon is too large on macOS Big Sur (not enough padding)

### ISSUE THREAD

**Issue by joanrieu** [xor-gate/syncthing-macosx#152]
Hello,

On macOS Big Sur, the tray icon does not fit with the rest of the system icons.
It does not have enough padding and therefore looks larger than the other icons.

![screenshot](https://user-images.githubusercontent.com/761962/116632349-ff2d2e80-a924-11eb-8856-1afef9a7031f.png)

Thanks!
Joan

(Seen on v1.15.1-1)

**Comment by xor-gate** [comment]
<img width="630" alt="Screenshot 2021-05-02 at 10 14 50" src="https://user-images.githubusercontent.com/1050166/116806781-8817b600-ab2f-11eb-91fc-a51ca10ed06c.png">
As you can see other applications like VideoLAN and Todoist have the same padding. System icons are indeed a little smaller. 

I'm not going to fix this.

**Comment by joanrieu** [comment]
This is just a case of other apps having the same issue.

Similar tickets are open on various projects and are in the process of being fixed:
https://github.com/keepassxreboot/keepassxc/issues/6074
https://github.com/OrangeDrangon/android-messages-desktop/issues/334
https://github.com/nextcloud/desktop/issues/2584
https://github.com/owncloud/client/issues/8378
