### ISSUE TITLE
Application icon does not respect macOS Big Sur design guidelines (rounded rectangle)

### ISSUE THREAD

**Issue by joanrieu** [xor-gate/syncthing-macosx#153]
Hello,

The icon of the application does not respect the guidelines for macOS Big Sur and it stands out from the rest (see screenshot below).

The guidelines from Apple are available over here: https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

In a few words, the icon should be a rounded rectangle of an Apple-specified size. As you can see in the screenshot, some apps have taken the simple route of just using a fill color with the regular icon inside.

Thanks,
Joan

![screenshot](https://user-images.githubusercontent.com/761962/116633295-1ec55680-a927-11eb-8165-5bf806f249ad.png)

**Comment by jakob** [comment]
I've started working on a modern squircle icon:
<img width="740" alt="Bildschirmfoto 2021-11-19 um 21 11 05" src="https://user-images.githubusercontent.com/198305/142685728-3f978317-ce9e-4741-8ec4-6865d8e88a27.png">

What do you think?

If you think that approach works, I'll make all sizes of the icon and make a pull request.

**Comment by xor-gate** [comment]
Hi @jakob thanks for your time and effort, for me it looks much better than I could design. Feel free to submit a PR.

**Comment by jakob** [comment]
I made a PR with the new icon.

I wasn't sure where to put the original vector file, so for now I am just attaching it to this issue here:

[Syncthing Icon macOS 11.zip](https://github.com/syncthing/syncthing-macos/files/7584586/Syncthing.Icon.macOS.11.zip)

(It's an Affinity Designer file)

**Comment by xor-gate** [comment]
A big thanks to @jakob for putting effort in this!
