### ISSUE TITLE
Allow to add commandline option, specially -audit

### ISSUE THREAD

**Issue by opensource21** [xor-gate/syncthing-macosx#154]
On commandline I can set -audit to get audit-log files. It seems impossible for syncthing-macos.
Since the ui only works with embedded syncthing, I don't see any workaroung.

**Comment by xor-gate** [comment]
Hi @opensource21, this is currently not possible to inject custom command-line parameters. What you could do is run syncthing from the terminal application on the commandline directly `/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing`. 

First you need to stop it from the tray icon menu:
<img width="481" alt="Screenshot 2021-05-05 at 17 48 18" src="https://user-images.githubusercontent.com/1050166/117170270-2a52ca80-adca-11eb-9d3a-cf2584f144bb.png">

**Comment by opensource21** [comment]
Thanks for the hint. I choose the following workaround.
In folder 
`cd /Applications/Syncthing.app/Contents/Resources/syncthing/ `
Rename the original file
`mv syncthing syncthing.org`
Created a file mysyncthing.sh	
```bash
echo "#!/bin/zsh" > mysyncthing.sh
echo "/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing.org -audit $@" >> mysyncthing.sh
chmod a+x mysyncthing.sh
```
and create a link
`ln mysyncthing.sh syncthing`

So I can be sure to always has audit enabled.
The audit-files can be found at `~/Library/Application Support/Syncthing/`.

Only drawback: At each update  I need to call
```
mv  /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing 	/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing.org 
ln /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing /Applications/Syncthing.app/Contents/Resources/syncthing/mysyncthing.sh
``` 

So I would really appreciate if you can make possibility to a permanent customization.

**Comment by xor-gate** [comment]
Dear @opensource21,

As requested I added (preliminary) support for adding "power user" arguments to syncthing. It is currently a hidden feature which is not available from the GUI because I have a not enough experience programming in Swift/Objective C and using XCode Interface Builder.

You can download a v1.16.1-2 release from https://build.syncthing.net/repository/download/SyncthingMacOS_BuildReleaseDmg/101990:id/Syncthing-1.16.1-2.dmg

And you should set the arguments from terminal this way:
```
defaults write com.github.xor-gate.syncthing-macosx Arguments '--audit --auditfile=/Users/jerry/staudtifilefromcfg.log'
```

See also the above commit.

Please let me know if it works for you. And consider [donating](https://github.com/sponsors/xor-gate) my hard work ;-)

**Comment by opensource21** [comment]
Works like a charm. Perfect solution in my eyes. I think persons who want this feature, will read the Readme.md and will be happy. I had tried to change the executable in defaults, but it can't be changed.

Thanks for your work. For me the issue can be closed.

**Comment by xor-gate** [comment]
The executable in the defaults is an old/deprecated feature. So yes this is not working (anymore). Have fun!

**Comment by xor-gate** [comment]
I have released [v1.16.1-2](https://github.com/syncthing/syncthing-macos/releases/tag/v1.16.1-2) which is the addition of this feature request.

**Comment by luckman212** [comment]
Just adding this note here related to debugging going on over at https://forum.syncthing.net/t/com-apple-provenance/19262/17

For anyone who wants to increase the logfile size using the macOS bundle, you can use:
```shell
# sets logfile size to 50MB, and keep the last 5 during logrotate 
defaults write com.github.xor-gate.syncthing-macosx Arguments '--log-max-size=52428800 --log-max-old-files=5'
```
And when you're done debugging, use this to revert things back to default:
```shell
defaults delete com.github.xor-gate.syncthing-macosx Arguments
```
I believe you need to fully quit the Syncthing app after each of these changes (not just stop/start the service) for it to take effect.

**Comment by xor-gate** [comment]
Commenting on your findings:

> I believe you need to fully quit the Syncthing app after each of these changes (not just stop/start the service) for it to take effect.

Yes the `Arguments` are loaded only on startup. Not when changed.
