### ISSUE TITLE
DMG doesn't open finder dialog

### ISSUE THREAD

**Issue by YeautyYE** [xor-gate/syncthing-macosx#156]
I tried to install Syncthing on M1, but nothing happened when I clicked.

**Comment by xor-gate** [comment]
This is weird, did you see the tray icon appearing at the right corner of your desktop?:

<img width="460" alt="Screenshot 2021-05-09 at 15 21 45" src="https://user-images.githubusercontent.com/1050166/117573844-6479e000-b0da-11eb-9063-22b7d18cd6ab.png">

**Comment by YeautyYE** [comment]
I clicked on the.dmg file and nothing happened, nor did the tray icon appear.

**Comment by YeautyYE** [comment]
I use the following command to open it
`hdiutil attach Syncthing-1.16.1-1.dmg`

**Comment by xor-gate** [comment]
You are the first one reporting this problem, maybe it has something to do with your system. A dmg should always open and show a finder dialog to install (drag and drop) the application. Luckily you had a workaround.
