### ISSUE TITLE
Constant beachballing...

### ISSUE THREAD

**Issue by 26tajeen** [xor-gate/syncthing-macosx#159]
I don't know if it's got something to do with the URI and API key but the application is **constantly** beachballing. The web interface responds fine.

**Comment by xor-gate** [comment]
Hi @lancelon,

Could you be a little more specific which macOS version and Syncthing macOS version you are using. Does the tray icon respond?

<img width="483" alt="Screenshot 2021-05-23 at 12 24 45" src="https://user-images.githubusercontent.com/1050166/119256628-e16c8580-bbc1-11eb-9bc4-18f60e93e54d.png">
