### ISSUE TITLE
Preferences windows will not open (due to missing default settings)

### ISSUE THREAD

**Issue by muellmaa** [xor-gate/syncthing-macosx#16]
The app starts, and sync thing runs. But the tray app is useless: it shows an error sign and I can only click on "Open", "About" and "Quit Syncthing". "Folders" and "Preferences..." aren't clickable - or nothing happens when clicking...

Ps. I'm using the most recent release und macOS Sierra. It's the same issue on my Mac Pro and on my Mac mini.

see the attached screenshot

any remedy for this issue? I had QsyncthingTray.app installed before and it was working perfectly.
![bildschirmfoto 2016-10-16 um 15 39 54](https://cloud.githubusercontent.com/assets/8938198/19417844/23be2642-93b7-11e6-9ea3-41c5cbffe3f5.png)

**Comment by xor-gate** [comment]
You need to set the preferences to where syncthing is running and the API key.

**Comment by muellmaa** [comment]
if I click on "Preferences" in the tray app, NOTHING happens...

**Comment by xor-gate** [comment]
Is the preferences window not poped-under other windows?

**Comment by muellmaa** [comment]
no. it's just not opening...

**Comment by xor-gate** [comment]
Which version are you running ? I build/develop from macOS Sierra. And v0.14.8-1 works fine.

**Comment by muellmaa** [comment]
I just downloaded this:
Syncthing-0.14.8-1.dmg, moved to applications and started... perhaps I'm doing something completely wrong then ;-)

**Comment by xor-gate** [comment]
Thats weird, it should "work out of the box" like you describe. Have you tried to quit and open it again?

**Comment by muellmaa** [comment]
yes. multiple times... it's the same on my Mac Pro and my Mac mini...

I thought the same: downloading, drag'n'drop and double-click should work :-S I mean no compiling is required, right? I'm not really a techie...

**Comment by xor-gate** [comment]
No the drag-and-drop is for users, with a builtin auto-updater. I'm clueless why no window is showing. Does no window open at all? Even the about window?

**Comment by muellmaa** [comment]
the about window appears normally

**Comment by xor-gate** [comment]
The preferences window should behave to same :=(

**Comment by muellmaa** [comment]
same thing on a MacBook Pro...

**Comment by xor-gate** [comment]
There are many downloads already, you are the first one reporting this. Could you send me a email to see if I can remote fix with teamviewer? (jerryjacobs1989 at gmail dot com)

**Comment by muellmaa** [comment]
email out, thx!

**Comment by muellmaa** [comment]
Terminal output:

2016-10-16 16:28:38.877 Syncthing[1883:66078] *** Assertion failure in -[NSButtonCell setStringValue:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504/AppKit.subproj/NSButtonCell.m:2391

**Comment by xor-gate** [comment]
It seems the default configuration loading fails. You need to open `Terminal.app` and write the default config with some commands:

```
defaults write com.github.xor-gate.syncthing-macosx URI "http://localhost:8384"
defaults write com.github.xor-gate.syncthing-macosx ApiKey "1234"
defaults write com.github.xor-gate.syncthing-macosx StartAtLogin "false"
```

**Comment by xor-gate** [comment]
This is where the magic happens:

https://github.com/xor-gate/syncthing-macosx/blob/master/syncthing/STPreferencesGeneralViewController.m#L24-L26

**Comment by xor-gate** [comment]
I have probably a fix commit in: https://github.com/xor-gate/syncthing-macosx/commit/afff54d64749e0cc028835cf0e7cd4e2bb2820dd

**Comment by xor-gate** [comment]
It should be fixed now for fresh installs. You can update: About -> Check for update. Could you verify it works?

You can read/delete all default application settings from the terminal:

```
defaults read com.github.xor-gate.syncthing-macosx
defaults delete com.github.xor-gate.syncthing-macosx
```

**Comment by muellmaa** [comment]
it's working perfectly now! thanks!

**Comment by xor-gate** [comment]
Awesome!
