### ISSUE TITLE
Context menu in Finder for enable/disable synchronization for individual folders or files.

### ISSUE THREAD

**Issue by LoginByCall** [xor-gate/syncthing-macosx#160]
It would be cool if a context menu is added to the finder from which you can enable or disable synchronization for individual folders or files.
This feature will greatly save disk space.

For example:
- Download here
- Clear here
- Delete from all

When clearing a local file (or folder), automatically created a zero-length file (or folder) with an extension, for example .synth, in order to be able to re-enable synchronization.

Example:
It was "letter.docx"
became "letter.docx.synth"

**Comment by xor-gate** [comment]
Selective sync is not a feature of Syncthing see also the forum https://forum.syncthing.net/search?q=selective%20sync

**Comment by LoginByCall** [comment]
> Selective sync is not a feature of Syncthing see also the forum https://forum.syncthing.net/search?q=selective%20sync

I have read previous requests.
Here is one of them.
https://forum.syncthing.net/t/selective-sync-selection/14210

The solution you proposed to use different folders does not suit to me, and this is problem relevant for many users.
I will give examples of specific cases.
Folder with audiobooks, folder with software distributions, folder with cinema, folder with different projects.
Most users are comfortable with breaking down content by meaning, and not by need now.
Each of these folders may be too large. They are all stored on my server. My other devices - smartphone, tablet, laptop, use different files from this set. As wisely remarked
As Richard Brooksby (rptb1) said, it is extremely silly to log into your server via ssh to just sync some files.
Using the synchronization mechanism for specific files, I can download exactly those books / distributions and materials that I need and not break the logic of placing content in folders.

p.s.: Why resist a burning request from users when they explicitly ask for help?
