### ISSUE TITLE
latest release tagged 1.17.1-1 but is actually 1.17.0-1 so causes endless update loop

### ISSUE THREAD

**Issue by luckman212** [xor-gate/syncthing-macosx#161]
the latest release is tagged 1.17.1-1 but the sparkle feed keeps seeing it as a new update because the actual bits on the disk are 1.17.0-1

![image](https://user-images.githubusercontent.com/1992842/120797978-b0b61580-c50a-11eb-8614-9eaf86d1e3db.png)

**Comment by xor-gate** [comment]
<img width="444" alt="Screenshot 2021-06-04 at 14 39 32" src="https://user-images.githubusercontent.com/1050166/120802400-ae6fad80-c542-11eb-9cc8-1e608b4726d2.png">

Fixed
