### ISSUE TITLE
Please provide gpg signatures for macOS dmg

### ISSUE THREAD

**Issue by jonathancross** [xor-gate/syncthing-macosx#166]
It would be nice to have gpg signatures for releases in this repo [just like other releases](https://syncthing.net/security/).
Apple developer code signing is great for most users, but for the tinfoil hat guys, how are we to know if the **_correct_** code signing key was used?  There is no web of trust for example and trust lies with Apple's verification.

**Comment by xor-gate** [comment]
For more trust in the official syncthing macOS application bundle it would indeed be necessary to sign the release dmg with the key "Syncthing Release Management <release@syncthing.net>". 

But in my opinion this is really thinfoil hat guys paranoid feeling of security:
- `syncthing` binary is signed and can be checked with [stsigtool](https://docs.syncthing.net/dev/release-signing.html#creating-and-verifying-binary-signatures-manually)
- `Syncthing.app` is signed with apple notarize mechanism
- Checksum file is created and gpg signed

@calmh could we add an extra teamcity job just like for generating the `sha1sum.txt.asc` file? Every release I will collect the notarized dmg and the new gpg signed checksum file for uploading to github. Thanks!

**Comment by xor-gate** [comment]
IMHO notarized syncthing binary and signed with stsigtool and notarized bundle is enough to be secure.
