### ISSUE TITLE
Compatibility with Mac OS X 10.9 (or lower)

### ISSUE THREAD

**Issue by mdarse** [xor-gate/syncthing-macosx#17]
Hi, what makes this project targets macOS 10.10 and above? Can I help to make this work on 10.9?

**Comment by xor-gate** [comment]
Hi @mdarse that is actually a very good question. I'm aware of some OSX foundation/cocoa API calls which are introduced in 10.10 and higher:

[NSWorkspace](https://developer.apple.com/reference/appkit/nsworkspace) [(use here)](https://github.com/xor-gate/syncthing-macosx/blob/master/syncthing/STApplication.m#L27)
[NSTask](https://developer.apple.com/reference/foundation/nstask) [(used here)](https://github.com/xor-gate/syncthing-macosx/blob/master/syncthing/XGSyncthing.m#L28)

Also usefull info are the [Foundation Changes in 10.10](https://developer.apple.com/library/content/documentation/General/Reference/APIDiffsMacOSX10_10SeedDiff/modules/Foundation.html)

For the rest I don't know, I'm not sure if there is a option/tool in Xcode to check API compatiblity.

**Comment by mdarse** [comment]
The `NSWorkspace` call is macOS 10.0+ (still it shows as 10.10+ in Swift tab, certainly because Swift wasn't released before).

On the other end, `NSQualityOfServiceBackground` is 10.10+. Ideally, we could have some version checking, using QoS when OS supports it, falling back to no QoS if not.

I'll try to make this work, but I'm not sure I can open even open the project on Xcode 6.2.

**Comment by xor-gate** [comment]
I'm building the project after push to github with travis continuous integration for xcode 7.1:
https://github.com/xor-gate/syncthing-macosx/blob/master/.travis.yml

Probably I can save it for an older Xcode for compatibility.

**Comment by xor-gate** [comment]
This explains some notes about building on newer OS X version for older systems:

https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html

**Comment by xor-gate** [comment]
And when methods are not available:

https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/cross_development/Using/using.html

**Comment by xor-gate** [comment]
I'm closing this, currently OS X 10.10 and higher is only support. Feel free to comment or create a pull request to support for 10.9.
