### ISSUE TITLE
Voice Control name of SyncThing Icon is "Idle"

### ISSUE THREAD

**Issue by justinrporter** [xor-gate/syncthing-macosx#171]
Using MacOS's [VoiceControl](https://support.apple.com/en-us/HT210539) feature, the name of the dock icon for SyncThing is "Idle" (or presumably any of the other values this can take depending on sync status), likely because that's what the tooltip reads:

![Screen Shot 2022-01-06 at 10 57 25 AM](https://user-images.githubusercontent.com/3531723/148420374-2e9eddfb-cd06-41e3-8081-aac83e31c448.png)

The result is that to select the Syncthing tray icon, the user must speak "select idle".

I think it should be an easy fix: rename the tooltip to "Syncthing (Idle)" or something.

For example, "Click Dropbox" works when Dropbox's tooltip is longer.

![Screen Shot 2022-01-06 at 10 58 07 AM](https://user-images.githubusercontent.com/3531723/148420485-534cb65c-1f33-4aca-91b8-551c98002bc5.png)

Thanks for the project, keep up the great work!

**Comment by xor-gate** [comment]
Hi @justinrporter,

At first, thanks for the generous one-time donation. It is indeed easy to fix and the dropbox tooltip is much more descriptive and complete. I will patch this before sunday evening and you can test if you want. I will let you know in this ticket.

Kind regards
Jerry

**Comment by xor-gate** [comment]
Hi @justinrporter, I have improved the tooltip which looks now similar as dropbox. You may test the unreleased but signed dist version 2 by manual installing from here <https://build.syncthing.net/viewLog.html?buildId=114784&buildTypeId=SyncthingMacOS_BuildReleaseDmg&tab=artifacts>. Please let me know if this is what you expect.

**Comment by xor-gate** [comment]
Forgotten to say how it looks now:
<img width="216" alt="Screenshot 2022-01-08 at 15 18 30" src="https://user-images.githubusercontent.com/1050166/148648049-1c50fbac-4232-4474-8652-aa6353622513.png">

**Comment by justinrporter** [comment]
It looks great! 

Thanks so much... I hope you feel like it's an overall improvement, not just for accessibility reasons. I use your app on all my macs, thanks for keeping things up to date and running smoothly!

Cheers!

**Comment by xor-gate** [comment]
I find it a good improvement also, I have no Dropbox or other cloud sync tools so I could not compare the tooltip. Actually this request did some un-dusting of the status handling code so with a new release the pause will also be correctly displayed. See also #172.

**Comment by xor-gate** [comment]
This issue is can be closed since commit has landed https://github.com/syncthing/syncthing-macos/commit/5faae151abee7e12cffb4416b233f63d8ae844b2. Feel free to comment.
