### ISSUE TITLE
On macOS 12.2 Syncthing is running but GUI doesn't show

### ISSUE THREAD

**Issue by supermaverickws** [xor-gate/syncthing-macosx#173]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/61172354/153544893-d002a016-f2be-49c6-a77e-f8f6fedeb2f1.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/61172354/153544907-3a4e3175-776f-450f-9908-390c96cdb7b1.png">

**Comment by supermaverickws** [comment]
Menu don't exist  too

**Comment by xor-gate** [comment]
This is weird. I'm running 12.0.1 macOS and have no issues. See screenshot:
<img width="1038" alt="Screenshot 2022-02-11 at 08 39 28" src="https://user-images.githubusercontent.com/1050166/153553697-729bcfaf-d80d-4c0c-a812-e0ec4d94edba.png">

@jakob this has probably something todo with feature addition #169, do you run latest macOS 12.2?

**Comment by xor-gate** [comment]
@supermaverickws some questions so we clear things up:

* Do you see the macOS bar icon?
* When you open Syncthing.app from Applications directly or via Launchpad does a preference window show?

<img width="634" alt="Screenshot 2022-02-11 at 08 44 07" src="https://user-images.githubusercontent.com/1050166/153554376-5959c3f3-b11a-479a-9de1-e51edde6b540.png">

<img width="311" alt="Screenshot 2022-02-11 at 08 45 58" src="https://user-images.githubusercontent.com/1050166/153554448-92927855-928f-444a-8241-174d329f3551.png">

My macOS 12.2 update is waiting installation.

<img width="780" alt="Screenshot 2022-02-11 at 08 48 15" src="https://user-images.githubusercontent.com/1050166/153554698-36dcf57f-33d4-4d8f-a56c-47bac785c744.png">

**Comment by jakob** [comment]
Did you uncheck the "Show in Menu Bar" checkbox? That would hide the icon.

You can check if the menu bar icon is hidden with the following command:

`defaults read com.github.xor-gate.syncthing-macosx`

If there is a line `"NSStatusItem Visible Item-0" = 0;` then the menu bar item is hidden. You can show it again by doing this:

1) locate sync thing in finder
2) double click Syncthing app icon
3) The SyncThing preferences should appear (it's possible the window is on a secondary screen, or partially off screen. Try looking for it in mission control if you can't find it)
4) check the "Show Icon in Menu Bar" checkbox to show it again

If that doesn't work:

1) Quit Syncthing with activity monitor
2) enable the status item with the following command: `defaults write com.github.xor-gate.syncthing-macosx "NSStatusItem Visible Item-0" 1`
3) start synct thing again
4) The menu bar icon should appear now

**Comment by jakob** [comment]
And I just wanted to say that Syncthing works as expected both on macOS 12.2 and on macOS 12.3 beta.

My guess is that @supermaverickws is surprised that you can make the UI disappear completely by hiding the menu bar icon, and maybe they don't realise you have to launch Syncthing again even though it is already running to make the preferences window appear.

**Comment by supermaverickws** [comment]
thanks.  It displayed When restarted system.

**Comment by dvnlgls** [comment]
Commenting since this shows up on google search.

If you can access the Syncthing web page, and are using a Mac with notch, the solution might be that you are having too many icons on the menu bar! This stumped me for a few minutes. My icon was hiding behind the notch! So I just removed an unused app icon and could see the Syncthing icon.
