### ISSUE TITLE
Status Unknown (Online) and Syncthing Service (Stopped) but API (Online)

### ISSUE THREAD

**Issue by SebDominguez** [xor-gate/syncthing-macosx#174]
- Synching version 1.19.0-1

Recent update show me an unknown (online) state on the status bar

<img width="505" alt="Capture d’écran 2022-02-28 à 16 03 30" src="https://user-images.githubusercontent.com/52816569/156006648-fab75e2a-c108-4e54-a855-39060de3a6e5.png">

Running macOS 12.2.1 (21D62)

**Comment by imsodin** [comment]
I might have pre-emptively moved and this is instead a support request:

This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by SebDominguez** [comment]
Thing is that Synching is running and working, but somehow the helper menu think the service isn't started
<img width="560" alt="Capture d’écran 2022-02-28 à 17 30 23" src="https://user-images.githubusercontent.com/52816569/156020719-e43c9c76-61fb-489a-aca8-982f2256225e.png">
.

**Comment by imsodin** [comment]
Ok, so my move action wasn't pre-emptive but the closing was - I shouldn't try to multi-task. Sorry for the confusion, I'll let @xor-gate pick it up from here :)

**Comment by xor-gate** [comment]
Probably syncthing is still running in the background so the bundle is unable to start it by itself
you could do -> Ctrl+space -> Activity monitor -> search for 'syncthing' (note the small letters) -> Then klik on the process and klik on the stop button.

**Comment by SebDominguez** [comment]
Yes it probably was the old process still running. The problem disappeared after I removed  SyncThing and then reinstalled it.
First time I use the auto update feature, maybe it needed a full reboot to sort itself.

**Comment by xor-gate** [comment]
Reinstall or reboot is normally not necessary

**Comment by eromoe** [comment]
Same issue, solved by reboot .  I think [SebDominguez](https://github.com/SebDominguez) is right,  `auto update`  cause this.
