### ISSUE TITLE
app does not start at login

### ISSUE THREAD

**Issue by kyle-03674** [xor-gate/syncthing-macosx#175]
Since using Syncthing on macOS Monterey (12.2 through 12.3) on my M1 MacBook Pro, the app will not automatically startup at login. I've tried toggling the Start at Login option in the menubar app's preferences, as well as System Preferences. No matter what I do, I need to start the app manually.

I'm currently at v1.19.1

**Comment by xor-gate** [comment]
<img width="532" alt="Screenshot 2022-04-02 at 16 12 53" src="https://user-images.githubusercontent.com/1050166/161387165-4f7627c9-2964-4bfc-a0da-f6593b4d9bc3.png">
Try to remove the entry from the list from system preferences -> Users and Groups -> User -> Syncthing. And close Syncthing. Then open it again and try to enable the start at login. Maybe the entry is pointing to the correct .app (maybe from the install dmg). Then check if the entry is present again and then reboot or login/logout to check if it is started.

**Comment by kyle-03674** [comment]
Syncthing doesn't show in my Login Items list even thought it is checked in the app's preferences. The install DMG is not mounted and I've restarted since installing the latest version. Ever since using the M1 machine on Monterey, it hasn't started on it's own. 

I haven't experienced this on the 15 other macOS Intel machines in the cluster. (I have no idea if the M1 or Monterey parts are relevant; I'm noting because it's a change.)

**Comment by xor-gate** [comment]
Does it work when you manually add Syncthing to the Login Items (with the + button)?

**Comment by xor-gate** [comment]
I'm unable to test this on M1 because I don't own one, but you are the first reporting and the M1 support is already there some time. Did it work before or did it got broken?

**Comment by kyle-03674** [comment]
I just tried this, adding it manually to Login Items, then logged out/in. It worked this time! Not sure why it did not work when I tried previously.  (Hmm... looking like user error now)  Thanks for your time!

By the way, I'm on v1.19.1-1, not 1.19.1.

**Comment by xor-gate** [comment]
Good it works now, does the tray icon now also see the item is started at login?

**Comment by kyle-03674** [comment]
Yes it does.
