### ISSUE TITLE
1.20.x breaks on MacOS Sierra

### ISSUE THREAD

**Issue by teizz** [xor-gate/syncthing-macosx#177]
1.19.2 Works as expected, starting 1.20.0 Syncthing fails to start and just loops with:

```
dyld: lazy symbol binding failed: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /Users/Teizz/Library/Application Support/Syncthing-macOS/syncthing
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security

dyld: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /Users/Teizz/Library/Application Support/Syncthing-macOS/syncthing
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security

SIGABRT: abort
PC=0x63399ee m=15 sigcode=0
```

This is on MacOS Sierra v10.12.6

**Comment by imsodin** [comment]
It was just pure luck that it worked before, already go1.17 requires mcaos >= 10.13. You need to update your system (preferred) or compile Syncthing yourself with an older go version. If you want help with that, please open a ticket on https://forum.syncthing.net

**Comment by teizz** [comment]
I'm aware I indeed need to update this system. It doesn't run much besides Syncthing and Apple is (was?) still releasing security updates for Sierra so I've not gotten around to it. I'd already resolved the issue for myself.

In any case, maybe update [the line in the README](https://github.com/syncthing/syncthing-macos/blob/develop/README.md?plain=1#L62) stating that from release v1.14.0-1 macOS 10.12 is required?

**Comment by babayoshihiko** [comment]
> 1.19.2 Works as expected, starting 1.20.0 Syncthing fails to start and just loops with:

I would like you to know I just had the same issue with you on my macos 10.12. I reintalled 1.19.2 and things are working now.

**Comment by xor-gate** [comment]
I have updated the readme v1.20.0 or higher needs at least macOS 10.13
