### ISSUE TITLE
macos version requirements are outdated

### ISSUE THREAD

**Issue by imsodin** [xor-gate/syncthing-macosx#178]
https://github.com/syncthing/syncthing-macos/issues/177#issuecomment-1120172994

> In any case, maybe update [the line in the README](https://github.com/syncthing/syncthing-macos/blob/develop/README.md?plain=1#L62) stating that from release v1.14.0-1 macOS 10.12 is required?

Since go1.17 (and whatever Syncthing version first used that) 10.13 is required. This info is bound to get out-of-date, so maybe just generically say that the requirement is the same of whatever the latest go version requires.

**Comment by xor-gate** [comment]
I have updated the version requirement, as most people who use the bundle don't going to dig into the golang docs so I will update the readme as necessary. I find general statement a little too broad.
