### ISSUE TITLE
Macos filesystem compatibility

### ISSUE THREAD

**Issue by goranx** [xor-gate/syncthing-macosx#180]
Apple filesystem is allowing certain characters that are not allowed on Windows, for some systems that have millions of files its very unpractical to find software or make a script that will do this fast enough. 
I think it would be very practical to make this a feature to rename(replace with some default character like "_") all illegal files so the other side can receive them.

**Comment by rasa** [comment]
A potential solution is in PR https://github.com/syncthing/syncthing/pull/7876.

**Comment by xor-gate** [comment]
Thanks @goranx for the report. The syncthing-macos project only ships the official syncthing application in a macOS specific bundle. When things in syncthing are bugged or features desired the main project  ([syncthing/syncthing](https://github.com/syncthing/syncthing/issues)) or [forum](https://forum.syncthing.net/) must be used.

I will close this issue as it is already in a ticket which @rasa suggested. Feel free to comment when things are not clear.
