### ISSUE TITLE
Make releases easier to find

### ISSUE THREAD

**Issue by jaxankey** [xor-gate/syncthing-macosx#19]
So, this is totally my ignorance of github, but it was actually difficult for me to find out where to download the actual dmg for this project. Somehow I couldn't find that link to "releases" in the "code" tab. It was like one of those things front and center in the fridge you would love to eat if you could only see it. I actually looked at this project a few weeks ago and gave up after 5 minutes of clicking around.

Anyway, for the blind like me, I would recommend including this link

https://github.com/xor-gate/syncthing-macosx/releases

On the main github page, and somewhere on the "shiny front page" as well. No worries either way, but it might help more of those with my mental deficiency find this amazing bundle. 

I would also consider opening up the wiki; I or someone else could add a brief tutorial on how to configure the firewall and port forward in apple land, which also wasn't initially obvious to me when I switched here from windows/linux.

Cheers,
Jack

**Comment by xor-gate** [comment]
I totally agree. I will do the following in some time:

* "Shiny front page" should have a download to the latest dmg page
* Github "README.md" should have a download link (instead of the badge only)
* The syncthing documentation should link to the "Shiny front page"

**Comment by jaxankey** [comment]
Thanks for making me feel better about my disability ;).
