### ISSUE TITLE
Reset Device ID after new mac setup via Apple's Transfer service

### ISSUE THREAD

**Issue by drsharp** [xor-gate/syncthing-macosx#199]
I set up a new M2 Macbook and as part of the setup I chose to just transfer application+data from my Intel macbook.

Everything works great, but Syncthing is on both machines with the same Device ID. I don't see any way to update that. I tried uninstalling (plus deleting ~/Library/Application Support/Syncthing), but upon re-install it was the same again.

Is there a better way to reset the Device ID in this case? I would think this would be a semi-common occurrence, where one sets up a new computer by transferring from the old computer, but then keeps both going as unique devices in the Syncthing local network.

**Comment by drsharp** [comment]
Never mind. Removing the Syncthing directory in `~/Library/Application Support` took care of it. It just took a little while. Syncthing generated a new Device ID. So I'm closing this. It's not a problem as I earlier thought it was. 👍

**Comment by xor-gate** [comment]
Yeah the certificate is where Syncthing derives it Device ID from. So be carefull when restoring the ~/Library/Application Support/Syncthing on both machines, then the same device id is present which is not good. Luckily you found a solution!
