### ISSUE TITLE
cmd+c / cmd+v not working

### ISSUE THREAD

**Issue by krisak** [xor-gate/syncthing-macosx#20]
Its just a little annoyance but when copying the API key (ive done this several times already) the preferences window does not have copy/paste shortcuts enabled. Luckily rightclick works.

**Comment by xor-gate** [comment]
Thanks for your report, I was already aware of this some time ago. I have a fix, not committed and released yet.

**Comment by xor-gate** [comment]
I have (forced pushed) a fix (https://github.com/xor-gate/syncthing-macosx/commit/b9e9bac1339d72199adf7f6fc406cf505f49087d) into master. I need to resolve some other stuff before I will create a release. I will leave this open until a new release is pushed.

**Comment by xor-gate** [comment]
Thank you for your report. A new release will be made soon. I'm closing this now.

**Comment by virusman** [comment]
Do you need help with the new release?

**Comment by xor-gate** [comment]
@virusman maybe you could verify if the latest master works as expected or it needs some patching.

**Comment by virusman** [comment]
Are there any unfinished features/fixes you planned for the release that I can help with?

**Comment by xor-gate** [comment]
@virusman I have created a milestone https://github.com/xor-gate/syncthing-macosx/milestone/2. And created a gitter chat (https://gitter.im/syncthing-macosx/Lobby#).

**Comment by virusman** [comment]
Re: the issue itself: I guess my changes from #4 got overwritten somehow. Copy/paste now works sometimes, Cmd+Z doesn't work.

**Comment by xor-gate** [comment]
I can reproduce this on the 0.14.8-2 build, not tested with master.
