### ISSUE TITLE
1.23.7 release

### ISSUE THREAD

**Issue by luckman212** [xor-gate/syncthing-macosx#200]
Has anything happened to the **syncthing-macos** builds? I got the notice that [1.23.7](https://forum.syncthing.net/t/syncthing-v1-23-7/20648) was out, and waited the usual 2-3 days for it to appear. But now it's been a week and it seems stuck... (if this is a manual process and you're busy enjoying your summer please forgive me for asking! I thought sometime a while back you'd automated this build process).

I remember reading a [conversation](https://forum.syncthing.net/t/syncthing-for-macos/2745/70) a while back about some changes with the automated builds for macOS. Not sure if that's related at all.

In the meantime, I compiled a 1.23.7 app bundle using [my own build script](https://github.com/luckman212/compile-syncthing-macos) in case anyone wants it. It's been working fine.

<img width="252" alt="image" src="https://github.com/syncthing/syncthing-macos/assets/1992842/f60c5de3-8ecb-424e-9658-d613613fff97">

**Comment by xor-gate** [comment]
Syncthing and Syncthing macOS are split projects. Syncthing macOS uses the Syncthing Core and disabled the automatic update mechanism for compatability reasons. So we need to semi-manually bundle the new Syncthing Core with the macOS GUI application. This needs manual intervention. Normally I catch up but for some reason I had missed it. Thanks for pointing out. Fixed and auto-updater should call the mothership soon with the new v1.23.7 release.

**Comment by luckman212** [comment]
Hey @xor-gate sorry to keep pestering you about this. But the auto-updater seems to need kickstarting again. [1.24](https://github.com/syncthing/syncthing/releases/tag/v1.24.0) dropped a few days ago.

**Comment by xor-gate** [comment]
1.24.0-1 has been released, it can take up to 30 minutes for the auto update server to refresh

**Comment by luckman212** [comment]
Thank you. Sorry to keep bothering about this.

**Comment by luckman212** [comment]
@xor-gate I am really sorry to nudge you about this. But I was wondering if there's a [1.25](https://github.com/syncthing/syncthing/releases/tag/v1.25.0) macOS build coming soon. Maybe worth waiting for 1.26 since that seems to be around the corner...

**Comment by luckman212** [comment]
🚀 I've updated the build script to support the upcoming 2.0 release.

<img width="252" alt="Image" src="https://github.com/user-attachments/assets/6f3ccd2a-c334-435b-98ca-a4b53bf3003a" />
