### ISSUE TITLE
v1.23.7 tagged as v1.27.7, which causes infinite software updates on Sparkle

### ISSUE THREAD

**Issue by niw** [xor-gate/syncthing-macosx#201]
Looks like v1.23.7 release is tagged [v1.27.7-1](https://github.com/syncthing/syncthing-macos/tree/v1.27.7-1),
which should be `v1.23.7` instead?
Because of this (I guess,) app keeps update itself to be 1.27. but which doesn't exist.

**Comment by xor-gate** [comment]
Oops! This step is unfortunatly one which needs to be done manually in the release management process it was a typo. Sorry for the inconvience. Should be fixed by now!
