### ISSUE TITLE
filename with special characters like ? doesn't maintain their name during sync

### ISSUE THREAD

**Issue by petterbergman** [xor-gate/syncthing-macosx#203]
If syncing a filename with the character "?" with a linux version, the filename will get changed.

Repro using a MacOS ver 1.24.0-1 with CasaOS (Linux) ver 1.23.5
1. Create a text file (I used TextEdit) and name it "Sync this?".
2. Put it in the default sync folder that is set to sync with another Syncthing install (in my case a Linux box)
3. Wait for file to sync

Result
The file sync, but the resulting file on Linux is named SDF8VM~B.RTF

Expected
To handle the ? character

Notes
I'm new to Syncthing and don't have the hardware to test again Mac to Mac or Linux to Linux. The CasaOS is basically a dockerized version of Syncthing, but it is slightly behind on the version, but the latest available to CasaOS. This could be a Mac to Linux only problem.

If you do it reverse, adding the file to Linux first, you get a special character unicode with ? in it, but still not the same filename.

**Comment by petterbergman** [comment]
Also happens for character : and / in filenames or folder names.

**Comment by er-pa** [comment]
The forward slash isn't really an allowed character anyways, and the colon is quite a special case too. The question mark here works just fine (MacOS <-> Ubuntu). Are you sure that CasaOS and the filesystem it uses can handle the question mark in file names?

**Comment by petterbergman** [comment]
Ah,
I did some more testing, and I think this is a problem with CasaOS and not Syncthing. I was using network fileshare to look at the CasaOS files and the filenames are scrambled in the network share. There's a built-in web app in CasaOS to view files and it seems the files are displayed correctly there. As it works for you with Ubuntu, I'll close this issue and open a new issue with CasaOS. Thanks for your time.
