### ISSUE TITLE
Release v1.25.0

### ISSUE THREAD

**Issue by Jip-Hop** [xor-gate/syncthing-macosx#204]
Hi, [v1.25.0](https://github.com/syncthing/syncthing/releases/tag/v1.25.0) has been out for a month. Would you have the time to release an updated version of syncthing-macos? Thanks in advance!

**Comment by xor-gate** [comment]
Done

**Comment by Jip-Hop** [comment]
Thanks!

**Comment by xor-gate** [comment]
I have now subscribed to github syncthing releases notifications, normally I would read my RSS feed but not frequently anymore. So hopefully releases will be more in sync in the future.

**Comment by luckman212** [comment]
Thanks @xor-gate 

I was about to comment over on https://github.com/syncthing/syncthing-macos/issues/200#issuecomment-1763491302 since [1.26 is now official][1]. But I saw this first. Will keep an eye out. Appreciate your efforts.

[1]: https://github.com/syncthing/syncthing/releases/tag/v1.26.0
