### ISSUE TITLE
Feature request: move "Check for updates" from About to Preferences

### ISSUE THREAD

**Issue by mstgrv** [xor-gate/syncthing-macosx#205]
I run syncthing-macos with the "Show in menu bar" preference disabled, and this makes it a tad annoying to update. The required workflow is:

1. Open Syncthing.app -> the Preferences window is displayed
2. Enable "Show in menu bar"
3. Click the menu bar icon and select "About"
4. Click "Check for updates" in the About box
5. Proceed with the Syncthing update -> Syncthing relaunches and shows the Preferences window
6. Untick "Show in menu bar" to hide the Menu bar item again

This is pretty convoluted. It'd be much simpler if "Check for updates" was available in the Preferences window directly, so the workflow would now be:

1. Open Syncthing.app -> the Preferences window is displayed
2. Click "Check for updates"
3. Proceed with update
4. Close preference window

**Comment by xor-gate** [comment]
Normally sparkle update should poll every 24h if there is an update available. It should not be necessary to manually check for updates. It is indeed not very handy when the icon is hidden. But as it is checked in the background I don't want to move it to preferences dialog as it is no preference.
