### ISSUE TITLE
Macos: no automatic scanning

### ISSUE THREAD

**Issue by cvlc12** [xor-gate/syncthing-macosx#208]
Hi,

After a fresh installation and setup (1.27 bundle) on Macos, incoming changes from the remote device (Linux) show up instantly, but local modifications are not propagated until I hit "Rescan".

Periodic scanning (every hour) seems to work. 

Is there anything specific to set up on Macos for automatic scanning to work, different from other OSes?

Thanks

**Comment by xor-gate** [comment]
No problem here almost instant file transfer, tried with the following versions:

- macOS 12.7.1 Monterey
- Syncthing for macOS v1.27.0-1

Make sure you have the Advanced setting per folder correctly set to "watch for changes". I'm not sure when you have a very large folder what the performance impact is and if Syncthing it then disables.

**Comment by cvlc12** [comment]
Thanks for your answer. I checked and the checkbox is properly enabled.

**Comment by xor-gate** [comment]
Which macOS version are you running and are you watching a big folder?

**Comment by cvlc12** [comment]
The folder is empty except for small test files. 
MacOS is 13.6.1.
I'm trying now with a folder created on the remote and then shared, and that seems to work. Not instantaneous but reasonable, maybe 5s. However on the first folder created on the Mac, it's still one way until a manual or periodic rescan.

[edit]
also works for a new share created from the Mac. All settings are the same. No idea what was wrong with the first.

**Comment by cvlc12** [comment]
Oh OK I think I got it. The first folder was stored in iCloud. I'm not used to Macs so I didn't see the difference.

Shares synced to local folders work.

Thanks !
