### ISSUE TITLE
insufficient space on disk for database

### ISSUE THREAD

**Issue by nudefireninja** [xor-gate/syncthing-macosx#209]
I don't know when this began (some time this year) because I don't use Syncthing often, but I now have a yellow notice when I open the web GUI that says:

> Error on folder "Default Folder" (default): insufficient space on disk for database (/Users/nfn/Library/Application Support/Syncthing/index-v0.14.0.db): current 35.3 GB < required 50 GB

and the Default Folder status is "Stopped". It must be a bug because I have 100 GB free space and the Default Folder is less than 100 MB (and it's the only folder I have configured with Syncthing).

Rebooting and updating Syncthing (it was on 1.22.2-1 before) did not fix it.

The mac with the issue is macOS 13.6 and the other mac is macOS 10.15.4 (and it is not showing the issue). Syncthing version now 1.27.1-1 on both machines.

Also, I am not sure but I think the other mac was shut off when this issue began as I rarely need to use it. There is also an Ubuntu machine which I have synced with before, but it is also not indicating a problem.

**Comment by xor-gate** [comment]
You could try the following:

1. Stop Syncthing from the tray
2. Open Terminal application
3. Execute `/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing --reset-database`
4. Execute `/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing --reset-deltas`
5. Start Syncthing application again
6. Open the web interface and see if it re-indexes

**Comment by acolomb** [comment]
The error message is pretty clear about the cause. It's not a bug I'd say. The database might not be big in itself, but Syncthing has a setting to avoid filling up the disks, so it will stop with said error when the free space goes below a certain threshold. That's usually set to 1 percent of the volume size (the one the Syncthing database resides on).

Free up space or reduce that setting to a lower percentage to fix the problem. No need to reset the database.

See https://docs.syncthing.net/users/config.html#config-option-options.minhomediskfree, under advanced configuration in the GUI.

**Comment by xor-gate** [comment]
Thanks for this clarification @acolomb. I didn't know about this. It is configurable from the web gui -> Actions -> Settings -> Minimum Free Disk Space.

**Comment by nudefireninja** [comment]
Thank you! I found out that the free space on the machine was indicated as 100 GB in Finder, but a huge chunk of that was [purgeable space](https://daisydiskapp.com/guide/4/en/PurgeableSpace/) which is supposed to be freed up automatically when needed. I used DaisyDisk to force purge it and then Syncthing started working again.
