### ISSUE TITLE
Override of `syncthing` Executable from .app to custom filesystem path via NSUserDefaults resets always back to bundle path

### ISSUE THREAD

**Issue by luckman212** [xor-gate/syncthing-macosx#212]
I've been running a custom compiled `syncthing` binary until https://github.com/syncthing/syncthing/pull/9430 is pulled into a release.

Today I replaced my macOS bundle with v1.27.4, and could no longer run the app due to Gatekeeper. Ugh.

I saw in the NSPrefs that there is a key to specify the Executable:

```
$ defaults read com.github.xor-gate.syncthing-macosx Executable
/Applications/Syncthing.app/Contents/Resources/syncthing/syncthing
```
But trying to set it:
```
$ defaults write com.github.xor-gate.syncthing-macosx Executable -string /usr/local/bin/syncthing
```
I found it immediately reverts back to the default one. Seems due to this code:
https://github.com/syncthing/syncthing-macos/blob/43c7282b80b6d99d07056e400f29e34bb4025bc9/syncthing/STApplication.m#L72-L77

Is there an env var or any other supported way to override the default syncthing binary with the app bundle?

_related:_

- https://github.com/syncthing/syncthing-macos/issues/14
- https://github.com/syncthing/syncthing-macos/issues/37
- https://github.com/syncthing/syncthing-macos/pull/76

**Comment by xor-gate** [comment]
See my commit above in the issue branch. I think it was because it was always set, instead try load. Then set when empty. It is untested, currently I have no environment to build dmg setup on my system. And the continuous integration with github actions doesn't create DMG in debug mode. Have a look.

**Comment by luckman212** [comment]
Looks like that will work! I can't test right at this moment but will try ASAP. 

In the meantime, I found that stripping `com.apple.quarantine` from the bundle, running the app and THEN replacing the syncthing binary seems to make Gatekeeper happy. It only checks for modifications to codesigned binaries upon first launch? TIL.

**Comment by xor-gate** [comment]
Could you test https://github.com/syncthing/syncthing-macos/releases/tag/v1.27.4-2 ?

**Comment by luckman212** [comment]
@xor-gate I will test by tomorrow, thank you for the build.

**Comment by luckman212** [comment]
@xor-gate LGTM ! 👍 

![screenshot_K0yOvWhb](https://github.com/syncthing/syncthing-macos/assets/1992842/5497a0f8-2ea7-4b07-8ec6-4137c37be6dc)

**Comment by xor-gate** [comment]
Great, this was modified without testing. But it was an easy fix :-)

**Comment by luckman212** [comment]
> _this was modified without testing_

# 😱

**Comment by xor-gate** [comment]
It would be nice to have it also in the documentation README for power users.
