### ISSUE TITLE
Wrong version in .dmg

### ISSUE THREAD

**Issue by rc-kerr** [xor-gate/syncthing-macosx#214]
When I install from the .dmg file labeled as 1.27.6-1, the actual version showing in the syncthing interface is 1.27.5.  Confirmed via multiple downloads/installations.  (And I am still having troubles with certain files not syncing, as was identified with 1.27.5.)

**Comment by orvpagadua** [comment]
same cant open the app. 

OS: Sonoma 14.4.1

**Comment by xor-gate** [comment]
I have double checked, but the version is not wrong. Please update to the latest v1.27.7-1.

**Comment by rc-kerr** [comment]
(For clarity, editing so that the Mac in question is denoted as 'A', while the other endpoint (on Linux) is 'B'.)

Okay, so I downloaded the new release, as suggested.  I installed it on A (specifically, I closed it using 'Quit Syncthing' from the tray menu, copied the .app from the new .dmg into the Applications folder (and selected 'Replace' when prompted); I even rebooted for good measure), and restarted syncthing.

When I select 'About' from the tray icon on A, it reports 1.27.7-2.  But in the syncthing web GUI on A, it still reports version v.1.27.5.  (And I still have the issue where both endpoints A and B show all folders as 'Up to date', but A shows that remote device B is still 'Syncing', with multiple out-of-sync items.)  The web GUI on B also confirms that remote device A is, in fact, running 1.27.5.

Not sure if I need to create a new issue, or if this will be seen...

**Comment by xor-gate** [comment]
Could you run the following commands in the terminal (note, its also with output):
```
(venv) jerry@Jerrys-iMac syncthing-macos % ps aux | grep syncthing
jerry            20614   0.0  0.6 35580884  92988   ??  SN    3:52PM   1:11.51 /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing -no-browser -no-restart -logfile=default
jerry            20612   0.0  0.0 35459316   5552   ??  S     3:52PM   0:00.54 /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing -no-browser -no-restart -logfile=default
```

And

```
(venv) jerry@Jerrys-iMac syncthing-macos % /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing --version
syncthing v1.27.7 "Gold Grasshopper" (go1.22.3 darwin-amd64) builder@github.syncthing.net 2024-05-08 06:02:01 UTC
```

**Comment by rc-kerr** [comment]
ps aux | grep syncthing
reid              1830 231.6  5.0 36825240 839476   ??  RN    4:26pm   1:36.67 /Users/reid/Library/Application Support/Syncthing-macOS/syncthing -no-browser -no-restart -logfile=default
reid              1840   0.0  0.0 410724048   1184 s000  R+    4:27pm   0:00.00 grep syncthing
reid              1829   0.0  0.1 35606784  13348   ??  S     4:26pm   0:00.68 /Users/reid/Library/Application Support/Syncthing-macOS/syncthing -no-browser -no-restart -logfile=default

 /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing --version
syncthing v1.27.7 "Gold Grasshopper" (go1.22.3 darwin-arm64) builder@github.syncthing.net 2024-05-08 06:02:01 UTC

Not sure why mine is running from a user library, when yours seems to be running from /Applications; I started it by double-clicking the app in the /Applications folder.

**Comment by xor-gate** [comment]
Easy fix, it seems the Executable is overwritten. Just quit syncthing. Then run `defaults delete com.github.xor-gate.syncthing-macosx Executable`, then run it again :-).

**Comment by rc-kerr** [comment]
That did the trick.  Thanks, much appreciated!

This might stem from the fact that I 'migrated' to a new Mac recently...  On my previous machine, this user account was unprivileged when syncthing was originally installed.  On the new machine, the account is an administrator.

**Comment by xor-gate** [comment]
Probably you had a very old installation. Previous Syncthing macOS copied the syncthing executable and then executed it from there. Then it did out-update in-place. Nowadays it is shipped and the internal auto-update is turned off.
