### ISSUE TITLE
macOS requirement bump

### ISSUE THREAD

**Issue by ahihi** [xor-gate/syncthing-macosx#216]
hi, just saw that the latest release bumped the macOS requirement from 10.13 to 12.7. this seems like quite a drastic change for what appears to be a bugfix release, so i am curious about why this was done and whether there is any possibility of restoring support for older versions (what would it require?).

**Comment by xor-gate** [comment]
Duplicate of #217, see other issue for comment

**Comment by iorbita** [comment]
I installed the new version, but the application still crashes...
I uninstalled the previous version (which consisted of a folder with files inside - see image) and installed the new one, but this doesn't change anything.
Is there a special procedure for installing the new version?

![syncthing](https://github.com/syncthing/syncthing-macos/assets/566221/ebd5ccec-4c5e-4d56-ab72-8d36a6bfcaa6)
