### ISSUE TITLE
Syncthing 1.27.7 not compatible with Mac OS 10.13.6?

### ISSUE THREAD

**Issue by iorbita** [xor-gate/syncthing-macosx#217]
Hi,
This morning Syncthing stopped working, when launching Terminal, the app crashes:

```
Last login: Wed May  8 15:05:12 on ttys000
/Applications/syncthing/syncthing ; exit;
iorbita-Mini:~ iorbita$ /Applications/syncthing/syncthing ; exit;
dyld: cannot load 'syncthing' (load command 0x80000034 is unknown)
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```
Could you confirm that version Syncthing 1.27.7 is no longer compatible with Mac OS 10.13.6 (High Sierra)?

Many thanks,
Lorenzo

**Comment by xor-gate** [comment]
I had some trouble with the automatic building with latest XCode in release mode. I have put some effort to make it compatible again. You manually need a one-time manual reinstall the v1.27.7-2 (second build) from the dmg. Keep in mind in the near future it will be really incompatible. The latest supported macOS by Apple is 12.x so it is possible the underlaying Golang Syncthing application can become incompatible.

**Comment by iorbita** [comment]
I installed the new version, but the application still crashes...
I uninstalled the previous version (which consisted of a folder with files inside - see image) and installed the new one, but this doesn't change anything.
Is there a special procedure for installing the new version?

![syncthing](https://github.com/syncthing/syncthing-macos/assets/566221/1ea1ce81-7008-45e5-97d0-fbd05cff5c49)

**Comment by xor-gate** [comment]
I have no idea why this happens, but you should use the Syncthing dmg file not the commandline version. It is probably incompatible with your 10.13.6 OS.

**Comment by xor-gate** [comment]
The latest dmg can be found here: https://github.com/syncthing/syncthing-macos/releases/download/v1.27.7-2/Syncthing-1.27.7-2.dmg

**Comment by xor-gate** [comment]
Or try an older one: https://github.com/syncthing/syncthing-macos/releases/download/v1.27.6-1/Syncthing-1.27.6-1.dmg

**Comment by iorbita** [comment]
... works with Syncthing 1.27.6-1 :)

Many thanks,
Lorenzo

**Comment by xor-gate** [comment]
So this means 1.27.7 is incompatible with macOS 10.13?

**Comment by iorbita** [comment]
... version 1.27.7-2 was crashing, so I assume this is due to incompatibility...?
