### ISSUE TITLE
autoupdate to v1.27.7-2 failed on macOS 10.13.6

### ISSUE THREAD

**Issue by hch0808** [xor-gate/syncthing-macosx#218]
autoupdate opened as usual and updated the app. After installation it showed an error window: "syncthing cannot be opened due to a problem".
Here is the error report from that window:
Process:               syncthing [786]
Path:                  /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing
Identifier:            syncthing
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Syncthing [785]
Responsible:           syncthing [786]
User ID:               501

Date/Time:             2024-05-09 07:56:18.944 +0200
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        970E6E03-2508-97CC-AFA3-60427CF4D8B7

Time Awake Since Boot: 2400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x9] <unknown>

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  cannot load 'syncthing' (load command 0x80000034 is unknown)

Binary Images:
       0x103642000 -        0x1043d1ff7 +??? (0) <8B2E323E-8012-3913-B8F8-95A2D26F3B29> (null)
       0x10dc7b000 -        0x10dcc5adf +??? (551.5) <CB9BFB56-4511-36F1-A546-891FF770C01C> (null)

Model: MacBookAir4,2, BootROM 135.0.0.0.0, 2 processors, Intel Core i7, 1,8 GHz, 4 GB, SMC 1.73f66
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE9), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.7f22, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256C, 251 GB
USB Device: USB 2.0 Bus
USB Device: FaceTime Camera (Built-in)
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Internal Memory Card Reader
Thunderbolt Bus: MacBook Air, Apple Inc., 8.1

**Comment by xor-gate** [comment]
You are out of luck and need to [manually downgrade to v1.27.6-1](https://github.com/syncthing/syncthing-macos/releases/tag/v1.27.6-1) and [manually disable the auto updater from commandline](https://github.com/syncthing/syncthing-macos?tab=readme-ov-file#disable-automatic-update-checker).

**Comment by xor-gate** [comment]
For reference, duplicate of #217, #219
