### ISSUE TITLE
Automatic browser open when started

### ISSUE THREAD

**Issue by krisak** [xor-gate/syncthing-macosx#22]
One little annoyance again. I have syncthing-macosx set to start on login which also starts browser every single time (with the webclient). I think this should be either turned off completely or there should be some setting to turn it off.

I guess its there for first time user but after that its annoying.

**Comment by bunam** [comment]
+1 ;)

**Comment by xor-gate** [comment]
You are right about this, I have this not released this yet but is fixed.
See https://github.com/xor-gate/syncthing-macosx/blob/master/syncthing/XGSyncthing.m#L22

**Comment by xor-gate** [comment]
A new release will be made soon, thank you for your report. I'm closing this, feel free to comment.
