### ISSUE TITLE
Option to disable a sign that shows sync

### ISSUE THREAD

**Issue by alexander-potemkin** [xor-gate/syncthing-macosx#223]
Thank you for a wonderful app and service!

From time to time, the menu bar icon shows a sign, signalling that the sync is happening / initiated from my Mac.

I would really appreciate it if it could become optional and be disabled - that's fine, if I shall use `defaults write` for that or any other manual intervention!

Thanks in advance!

**Comment by xor-gate** [comment]
In understand your use-case to have a static menu bar icon. But other icons also change when things are happening like the network/wifi icon. This behaviour should not be power-user or GUI controlled using the `defaults write`. If people change it "by accident" the icon stays static. It gives a small exclamation mark when something is wrong or failed. The syncthing-macos wrapper is a frugal application where I don't want to many turning knobs.

**Comment by alexander-potemkin** [comment]
Thank you for the explanation. I don’t mean static - explanation mark makes perfect sense on the icon, like on WiFi, for example.

But my WiFi icon doesn’t blink every minute or so, indicating that it search for the available networks.

That is exactly my intention here as well - avoid menu bar icon blink - display shortly sync micro-icon inside of itself.

**Comment by xor-gate** [comment]
I understand, you just wanted to "silent" the sync status icon. This is a very niche status filter, not convient IMHO.

**Comment by alexander-potemkin** [comment]
I see, thanks. And what is the purpose of this activity icon on menu bar icon?
