### ISSUE TITLE
Syncthing MacOS connections to a lot of outside servers

### ISSUE THREAD

**Issue by joedima** [xor-gate/syncthing-macosx#224]
Why is Syncthing connecting to so many outside servers, like in countries that in countries I not have business connecting to?

**Comment by tomasz1986** [comment]
Please check https://docs.syncthing.net/users/faq.html#why-does-syncthing-connect-to-this-unknown-suspicious-address.

**Comment by xor-gate** [comment]
@joedima when behind NAT P2P client/servers are unable to see each other except for opening ports at least on one side. In you case a secure relay server is used to proxy data behind double NAT. Yes you need to know some basics about networking. You could disable relaying with: Go to web UI (e.g 127.0.0.1:8384) -> Settings -> Connections -> Enable relaying, but **this will break transfers**.
