### ISSUE TITLE
SyncThing version update, seeming version contradiction...

### ISSUE THREAD

**Issue by SalishSea420** [xor-gate/syncthing-macosx#225]
First post to the forum but I have been using SyncThing for several years with very few issues. I do have fairly large functional problem but first this question...

When I open the SyncThing About dialog, it reports that I am running version 1.6.1-1 and when I click on the "Check for Updates" button, after a few moments it reports that I am up to date. Screen shot attached.

When I click on the "Project Page" link I find that the latest version is actually 1.27.10. When I originally installed this bundled version of SyncThing for the Mac it was my understanding that is would update automatically. What am I missing?

Macbook Pro and Mac Pro, both are running Ventura 13.6.7 (22G720) 

![SyncThing_About_Dialog](https://github.com/user-attachments/assets/f9aeb723-07ad-4269-9ce3-f43f7c8766f7)

**Comment by xor-gate** [comment]
There where some versions where the update endpoint has changed. Better download the latest version and overwrite the current one. Then you will get updates again.

**Comment by SalishSea420** [comment]
Success, thanks
