### ISSUE TITLE
Brew caskroom

### ISSUE THREAD

**Issue by krisak** [xor-gate/syncthing-macosx#23]
Since this is best syncthing client wrapper for osx i think it should be in caskroom. Its used by more and more people. 

Ive never made cask (https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) but i guess there is nobody who has experience with that (or uses caskroom) i will have to make it somehow.

Putting it here just for lovely someone who made cask before and could do it more easily :))

**Comment by xor-gate** [comment]
I'm using caskroom for some applications, it would be nice to have syncthing-macosx indexed. Keep in mind the upgrade mechanism of the OSX GUI is done with Sparkle and is in depended from syncthing updater and caskroom updater.

**Comment by krisak** [comment]
Why this would be a problem? I know that its just matter of one instal and then your client keeps itself up to date. The thing is Caskroom cant update aplications anyway (not yet anyway). It also used to be not very good but now its much better.

I see caskroom more like convenience when you format your computer and you do first time batch install of open-source apps through shell script.

**Comment by xor-gate** [comment]
It is no problem, but people should keep that in mind. I totally agree with your comment.

**Comment by LeonardoGentile** [comment]
I can't find it with cask search so I guess this was never done?

**Comment by xor-gate** [comment]
Thats right, no brew is available yet.

**Comment by krisak** [comment]
I gave it some time but honestly lost interest quickly since it wasnt that straightforward and it updates itself.

Sorry.

**Comment by xor-gate** [comment]
That's no problem, both syncthing-macosx (sparkle) and syncthing (upgrade server) itself update when updates are pushed.

**Comment by xor-gate** [comment]
Thanks guys for the report, I'm not going to support this distribution channel. As syncthing and syncthing-macosx have their own stable upgrade/install channel. I'm closing this but feel free to comment.

**Comment by ssbarnea** [comment]
Please reconsider this, `brew` is ubiquitous and much better than any internally implemented upgrade mechanism.

You do not have to update the cask on new releases if the app already has the ability to upgrade itself, still for initial installation brew is the *right* way.

**Comment by xor-gate** [comment]
Other people are free to add it to brew. But it won't be initiated from the syncthing-macosx project.

**Comment by fturcheti** [comment]
I've [just created a cask][1] for `syncthing-macos`. 
Now it's possible to install it with `brew cask install syncthing-app`.

[1]: https://github.com/Homebrew/homebrew-cask/pull/50623
