### ISSUE TITLE
Syncthing app doesn't resolve `syncthing.localhost` to `localhost` (unlike Chrome and Firefox)

### ISSUE THREAD

**Issue by lgarron** [xor-gate/syncthing-macosx#232]
While debugging https://github.com/syncthing/syncthing-macos/issues/231 I found that even though I had set my URL to `https://syncthing.localhost:8384` (which I have configured with a trusted certificate), Syncthing has rewritten this to `http://syncthing.localhost:8384`. This seems to cause the API check to fail.

I don't think it should be rewriting the URL like that.

EDIT: see https://github.com/syncthing/syncthing-macos/issues/232#issuecomment-2527037817

**Comment by lgarron** [comment]
Hmm, looks like the code is trying to look up the scheme through https://github.com/syncthing/syncthing-macos/blob/f06374145368049673050c26dc868dc8e0fe0271/syncthing/XGSyncthing.m#L179-L185

I definitely have `Use HTTPS for GUI` configured in the web UI, and `~/Library/Application Support/Syncthing/config.xml` contains `<gui enabled="true" tls="true" debugging="false" sendBasicAuthPrompt="false">`

So something is going wrong with this calculation.

**Comment by xor-gate** [comment]
The code is only executed first run to load settings from the XML: https://github.com/syncthing/syncthing-macos/blob/f06374145368049673050c26dc868dc8e0fe0271/syncthing/STApplication.m#L92-L93

**Comment by lgarron** [comment]
> The code is only executed first run to load settings from the XML:

The API check fails due to this issue even if the app is restarted.
Did you mean to comment on https://github.com/syncthing/syncthing-macos/issues/231 ?

**Comment by lgarron** [comment]
I tried debugging this in Xcode for an hour, and I still can't figure out what's causing the `https://` to be dropped.

I can run the following:

```shell
defaults write com.github.xor-gate.syncthing-macosx URI -string "https://syncthing.localhost:8384"
```

However, this results in even more red dots in the menu, even though Syncthing is successfully running and available from the web UI:

![clipboard](https://github.com/user-attachments/assets/8be74692-a4f9-4be5-875e-8e79362bd0f0)
![clipboard](https://github.com/user-attachments/assets/c5cad351-aef2-409d-a74a-95033f995cba)

**Comment by lgarron** [comment]
Ah, okay, I finally figured it out.

Safari (and the underlying network library) do not [let localhost be localhost](https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-let-localhost-be-localhost). This is very unintuitive if you mostly use Chrome and Firefox.

Therefore, this requires an entry in `/etc/hosts` to work:

```
127.0.0.1 syncthing.localhost
```

As someone who likes to namespaces `localhost` servers using subdomains, I guess I can live with that. This might benefit from being documented as a caveat in Syncthing docs, but I haven't found a good place for it to send a PR.

**Comment by xor-gate** [comment]
Thanks for reporting, but as you are doing non-standard things which are not supported in macOS by default. I will close this. Syncthing.app should be simple, and having this domain name for localhost service and localhost https is not the default setup. Most of the time people know then what they are doing.
