### ISSUE TITLE
Cannot toggle "start at login"

### ISSUE THREAD

**Issue by svandragt** [xor-gate/syncthing-macosx#25]
When I open the preferences "Start at login" is ticked for me. 
* I untick it
* I press the close button on the window. 
* I reopen the preferences

Expected: "Start at login" is unticked
Observation: "Start at login" is ticked.

Also I suspect it's not changing whether Syncthing is launched at login, but I haven't rebooted yet. I assume I should see a Lingon message because it monitors login items, but I didn't.

0.14.8-2

**Comment by xor-gate** [comment]
Probably currently it is only stored/removed when the save button is clicked. You can see it by putting `Preferences - Users & Groups -> Login items` next to it and try it.

The solution would be to sync the configuration immediate after window is closed.

**Comment by svandragt** [comment]
The save button is greyed out and is never enabled regardless of changes to the URL, API Key or the start at login button.

**Comment by xor-gate** [comment]
You first have to "test" the URL and API key if a connection could be made, but that must be separated from the saving of the "start at login" config option.

**Comment by svandragt** [comment]
I see it is saved now, thanks for your help xor-gate.

The missing step for me was that I had to enter GUI Listen Addresses and API Key from the Syncthing Web UI Settings into the Syncthing menubar preferences screen, and press test. The test button turns green. 

I can then toggle the startup on login checkbox, press test which enabled the save button, then save. Only then is the "Start at login" checkbox saved.

I guess as a new user I would have assumed that the web UI links up with the syncthing proces without my help, but that's ok. Thanks again.

**Comment by xor-gate** [comment]
Yes you are right, that is a good assumption. There is already some work prepared to have it auto-configured and link with the syncthing process. I will reopen this as it is not 100% intuitive and we need some work on this.

Thanks for your report!
