### ISSUE TITLE
Folders menu item remains empty

### ISSUE THREAD

**Issue by enaloha** [xor-gate/syncthing-macosx#38]
As the subject says, I don't see my folders listed in the menu:

![image](https://user-images.githubusercontent.com/13284542/29255714-a9cd6822-803f-11e7-800a-2c8525228d2b.png)

Is there a setting I need to change?

**Comment by xor-gate** [comment]
Are you sharing any folders, and does the tray is able to connect to syncthing? You should verify the preferences are correct (preferences menu item, and check with the test button) and it is able to connect to syncthing.

**Comment by enaloha** [comment]
I am sharing several folders and they work just fine. I am presently syncing two macs and one NAS without any problems. The Macs just don't show my properly syncing folders...

![image](https://user-images.githubusercontent.com/13284542/29259782-ebec47b6-8060-11e7-8e78-79c398270130.png)

**Comment by xor-gate** [comment]
Thats a weird situation, you are the first one reporting this problem.

**Comment by enaloha** [comment]
Okay, so I bit the bullet and completely reinstalled Syncthing on both Macs and that fixed the folder issue. It took a while to recreate the sync relations, but ultimately it was worth it.

**Comment by xor-gate** [comment]
Did you have an older installation (pre v0.14.33) and copied the new installation v0.14.33-1 over it? Or are you a first time user since v0.14.33? Now your problem went away it is difficult to tell why this has happend.

**Comment by enaloha** [comment]
Indeed, I installed over an older installation. In fact, that was one of the thoughts I had that could explain this. But all is good now.

**Comment by xor-gate** [comment]
"Check for updates" currently doesn't announce latest (v0.14.33) as it won't upgrade due to changes in bundle package signing. Its still a known issue that we need to announce the upgrade to v0.14.33 must be manually applied.
