### ISSUE TITLE
Feature Request: Add uninstall directions to readme.md

### ISSUE THREAD

**Issue by skilfullycurled** [xor-gate/syncthing-macosx#41]
Hi,

First off, thank you so much for this application.  For people who are not as binary savvy such as myself, this made it wonderfully easy to install.

Unfortunately, for reasons having nothing to do with your program, I need to uninstall it.  Naturally I suspect one uninstalls the application from the application directory.  However, if one were to install from binary syncthing appears to create a few dot files/folders.  Not sure if your installation via dmg does the same, but it'd be great to know.

Thanks again!

**Comment by xor-gate** [comment]
On Mac OS X you drop the application from the Application folder to your trashbin. But there are kept some files, indeed the "dotfiles". Which are located under `$HOME/Library/Application Support/Syncthing ` for OS X, these files are the configuration, encryption/profile files and the database cache (see https://docs.syncthing.net/users/config.html#description)

**Comment by skilfullycurled** [comment]
Thanks!  Much obliged.

Re: updating the documentation, I think it'd be good to have something as simple as a link to this issue or you can copy what you wrote directly verbatim.  

Syncthing-macosx makes it so easy to get started with Syncthing which is great for intermediate users who might not know how to install from binaries or don't want to install a package manager.  Searching for the osx uninstall process on the syncthing forums only yields  threads which relate to uninstalling the osx binaries.  So you sort of have a situation where it's easy to get in but difficult to get out.

Thanks again!

**Comment by xor-gate** [comment]
Great, will look into that. I have started an native implementation due to the lack of a nice and clean wrapper. I still have some ideas to improve it but not implemented yet (e.g backup of config and profile). Also something like dropbox overlays in finder "stuff is in sync, stuff is syncing"  icons are very nice to have.

**Comment by xor-gate** [comment]
Thank you for your feedback. It has been fixed https://github.com/xor-gate/syncthing-macosx/commit/e9f9174cec77b3bf6b602edf581d7f31e26e6ed7
