### ISSUE TITLE
Folders no longer sorted alphabetically after 0.14.48 update

### ISSUE THREAD

**Issue by mstgrv** [xor-gate/syncthing-macosx#49]
The Folders menu within syncthing-macosx used to sort folders alphabetically, but that's no longer the case after the 0.14.48 update, my folders are now sorted pretty much randomly

**Comment by xor-gate** [comment]
Yes we should alphabetically sort in the GUI after reading it from syncthing API.

**Comment by mstgrv** [comment]
Is there a way to manually do this at the moment? It's weird that the syncthing-macosx Folders menu was perviously listing everything alphabetically, but it only became random after the 0.14.48 update was installed. I'm using syncthing-macosx on 2 computers and it's happened on both.

**Comment by xor-gate** [comment]
We have never sorted it, so it must be a undocumented feature of the syncthing API. There is no way to sort it by hand.

**Comment by mstgrv** [comment]
From the devs [here](https://forum.syncthing.net/t/folder-list-no-longer-sorted-alphabetically-in-actions-advanced-as-of-0-14-48/11765/2)

> The advanced settings dialog shows things as they are in the config. In the config, folders are sorted by their folder ID. That’s not necessarily an order that makes sense for humans, who rather look at the label. I think it’s “always” been this way.

> Syncthing-macosx should sort in the GUI in a way that makes sense for humans. I see there is already an issue on it, so that’s good.

**Comment by xor-gate** [comment]
I have tried to fix it, but my Objective C skills are shortcomming. @virusman I tried to use `-[NSArray sortedArrayUsingSelector:]` but throws and exception. We should sort the result of `getFolders` before building the menu list (here https://github.com/xor-gate/syncthing-macosx/blob/master/syncthing/STApplication.m#L166).

**Comment by xor-gate** [comment]
Hi @mstgrv I have polished my objective C skills a little and seems to work now with the fix in #51. @virusman could you have a look?
