### ISSUE TITLE
Nothing happens when I click on 'preferences'

### ISSUE THREAD

**Issue by rjmackay** [xor-gate/syncthing-macosx#5]
I've installed the app, and its showing up in the status bar:
![unspecified](https://cloud.githubusercontent.com/assets/1050166/17473332/3dca3af0-5d50-11e6-8c3c-7553a65a4ed3.png)

Selecting 'open'  brings up syncthing in the browser. But 'preferences' does nothing.
Possibly related: its not listing folders either.

**Comment by xor-gate** [comment]
Which release version are you using? With release `0.14.3-1` there where some GUI changes. I'm running OS X 10.11.5 in bright mode (as I see you are running in dark mode).

**Comment by rjmackay** [comment]
I'm running https://github.com/xor-gate/syncthing-macosx/releases/tag/v0.14.3-1
.. not sure what was wrong but this appears to be working now.

**Comment by xor-gate** [comment]
Weird, maybe there was something wrong with the focus. If there are any other problems or glitches don't hesitate to open a new issue. Thank you for your feedback!

**Comment by rjmackay** [comment]
It was focus related. When it started working I discovered I had a stack of preferences dialogs open, all somehow trapped behind another window.

**Comment by xor-gate** [comment]
Today I have created a few releases, where the notable feature is a auto-update mechanism.
