### ISSUE TITLE
Activity doesn't update the status icon

### ISSUE THREAD

**Issue by xor-gate** [xor-gate/syncthing-macosx#7]
Currently when the status is `syncing` or `paused` it is not shown. The only implemented status is `error` or `normal` and is derived from the ping endpoint. Fetching the global state needs to be investigated.

**Comment by xor-gate** [comment]
I'm currently not sure how to fetch the global state from the API. I need to investigate further.

**Comment by virusman** [comment]
We need to use this API to monitor syncthing StateChanged events:
https://docs.syncthing.net/dev/events.html

**Comment by virusman** [comment]
#28 implements this, except for paused state (it's not a state from REST API standpoint, it's a configuration value).
