### ISSUE TITLE
Fix package signing

### ISSUE THREAD

**Issue by rjmackay** [xor-gate/syncthing-macosx#8]
It not reasonable to disable gatekeeper for my whole machine to install a single application. Any idea when package signing will be fixed?

**Comment by xor-gate** [comment]
Hi @rjmackay, 

It will be the first thing i'm going to fix but I first need to investigate why the .app is modified after signing in the first place.  Hopefully in the upcoming weeks as time permits.

As reference: http://stackoverflow.com/questions/22458027/mac-dmg-oddity-signing-and-damaged-applications

**Comment by justinclift** [comment]
Taking a quick look here (I'm no expert though), it seems to be a problem with the bundled Sparkle framework:

```
$ codesign --verify --verbose --deep Syncthing.app
Syncthing.app: a sealed resource is missing or invalid
In subcomponent: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/Sparkle.strings
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUAutomaticUpdateAlert.nib
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdateAlert.nib
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdatePermissionPrompt.nib
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/Sparkle.strings
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUAutomaticUpdateAlert.nib
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdateAlert.nib
file added: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdatePermissionPrompt.nib
file missing: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj
file missing: /Users/jc/tmp/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj
```

There seem to be two sets of strings (fr_CA, pt) modified from when it was signed.

It might be as simple as just needing an updated version of the Sparkle framework, or just re-signing it. :smile:

**Comment by xor-gate** [comment]
Hi @justinclift thanks for you help!

I have read the sparkle documentation:

> Apple code signing
> 
> If you are code-signing your application via Apple’s Developer ID program (which is recommended for macOS 10.8+), Sparkle will ensure the new version’s author matches the old version’s. Sparkle also performs basic (but not deep) validation for testing if the new application is archived/distributed correctly as you intended.
> 
> Note that embedding the Sparkle.framework into the bundle of a Developer ID application requires that you code-sign the framework with your Developer ID keys. Xcode should do this automatically if you let it “Code Sign on Copy” Sparkle’s framework.
> You can diagnose code signing problems with RB App Checker app and by checking logs in the Console.app.
> If you decide to both code-sign your application and include a public DSA key for signing your update archive, Sparkle allows issuing a new update that changes either your code signing certificate or your DSA keys. Note however this is a last resort and should only be done if you lose access to one of them.

The project uses the "Code Sign on Copy" for the Sparkle framework. But this seems to be a different problem. I have found another nice tool to check the validity with more output (GUI): [RB App Checker Lite
](https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12)

Which gives:
```
Evaluating the application “Syncthing”.

The application was signed by “Apple Root CA”, “Mac Developer: jerryjacobs1989@gmail.com (TT7GM4W59N)”.
	The (unverified) signing-time is: 23 Aug 2016 19:27:13.
	The object code format is “app bundle with Mach-O thin (x86_64)”.
	The signature contains the Team ID “C24U83K674”.
	Both bundle and signing identifiers are “com.github.xor-gate.syncthing-macosx”.
	The signature specifies implicit requirements. ￼
	The signature specifies resource rules (v1). ￼
	The signature specifies resource rules (v2). ￼
	➤ Requirements and resources didn't pass static validation. ￼ ￼

The code signature has the UUID “CAE07AC2-B487-88EE-E762-905692B17C16”.
	Executable code for x86_64 has the UUID “D55BA232-79EB-3AA7-86C5-978EC2989411”.

A signing-time snapshot of the application’s Info.plist was found. ￼
	Version 0.14.5 (140500) Copyright © 2016 Jerry Jacobs (github.com/xor-gate). All rights reserved.

The signature contains 3 certificates. ￼
	Certificate “Apple Root CA”: ￼
		Your keychain contains this trusted root certificate.
		Will expire on 09 Feb 2035.
	Certificate “Apple Worldwide Developer Relations Certification Authority”: ￼
		Will expire on 07 Feb 2023.
	Certificate “Mac Developer: jerryjacobs1989@gmail.com (TT7GM4W59N)”: ￼
		Will expire on 07 Aug 2017.
		SHA1 fingerprint: “8433783E947D054D7B88A70B0ACDB95B9CF3DAAF”.
		Team ID or Organizational Unit: “C24U83K674”.
			This matches the Team ID contained in the signature.

The application is not sandboxed.

There is one embedded framework. ￼

10 auxiliary executables have been found. ￼
	One file is invisible in the Finder. ￼ ￼
	6 executables are unsigned. ￼ ￼
	One executable is signed by  “Apple Root CA”, “Developer ID Application: Jakob Borg (LQE5SYM783)”. ￼
	3 executables are signed by  “Apple Root CA”, “Mac Developer: jerryjacobs1989@gmail.com (TT7GM4W59N)”. ￼
	4 executables are in the Resources folder. ￼
	One executable file has no executable permissions, but should. ￼ ￼
	Different executables are using the same signing identifier “org.sparkle-project.Sparkle”. ￼
	Different executables are using the same bundle identifier “org.sparkle-project.Sparkle”. ￼
```

And:

```
Error details: “-67054: a sealed resource is missing or invalid” {
	Error in subcomponent: Contents/Frameworks/Sparkle.framework
	Resources added: 
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUAutomaticUpdateAlert.nib
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdateAlert.nib
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/Sparkle.strings
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdatePermissionPrompt.nib
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUAutomaticUpdateAlert.nib
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdateAlert.nib
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdatePermissionPrompt.nib
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/Sparkle.strings
	Resources missing: 
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj
		Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj
}
```

**Comment by justinclift** [comment]
Yeah, it's probably a good idea to ask the Sparkle guys, as the `Resources added` and `Resources missing` indicate things in their signed file set unexpectedly.  They probably know about this already, and have re-signed them since. 😉 

As a quick workaround, you could sign the Sparkle framework bundled inside your Syncthing.app, but it's probably better to ping the Sparkle guys first. :smile:

**Comment by xor-gate** [comment]
This is weird, when I don't put the .app into the DMG then it is not broken! Can you guys test out?

https://github.com/xor-gate/syncthing-macosx/releases/download/v0.14.5/Syncthing-0.14.5-signed.zip

**Comment by justinclift** [comment]
Yeah, that one seems fine to me:

```
$ codesign --verify --verbose --deep Syncthing.app
Syncthing.app: valid on disk
Syncthing.app: satisfies its Designated Requirement
```

**Comment by xor-gate** [comment]
I must say, pushing the .app into the dmg is not the best way how it is done currently. Probably the script will break somewhere. Needs some investigation...

**Comment by justinclift** [comment]
Ahhhh, found something interesting.  The end part of the "unzip" output on your zip file was:

```
finishing deferred symbolic links:
  Syncthing.app/Contents/Frameworks/Sparkle.framework/Resources -> Versions/Current/Resources
  Syncthing.app/Contents/Frameworks/Sparkle.framework/Sparkle -> Versions/Current/Sparkle
  Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj -> fr.lproj
  Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj -> pt_BR.lproj
  Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current -> A
```

Both the fr_CA.lproj and pr.lproj look like links.  Maybe your .dmg creation process isn't doing the links correctly?

**Comment by xor-gate** [comment]
Yeah probably how the DMG ramdisk is created and files are copied into is breaking it:
https://github.com/xor-gate/syncthing-macosx/blob/master/3thparty/github.com/andreyvit/create-dmg/create-dmg

**Comment by justinclift** [comment]
If you need an alternative (super simple) way to create .dmg's from your app, you can copy ours if it helps?  Example .dmg here:

* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.9.0/DB.Browser.for.SQLite-3.9.0.dmg

**Comment by justinclift** [comment]
That's ironic.  `create-dmg` was the first thing we tried too (a few weeks ago), but it was too buggy.  Went with https://github.com/LinusU/node-appdmg instead.  1 min, and I'll dig up the bits.

**Comment by xor-gate** [comment]
I think I hacked the script. It seems the creation with hdiutils breaks the filesystem. Searched stackoverflow:
http://stackoverflow.com/questions/6081503/automating-dmg-build-in-xcode-4-0

**Comment by justinclift** [comment]
The bits:

* The command we run: https://gist.github.com/justinclift/38887c1cfe480adfb11b#file-build_sqlitebrowser_nightly-sh-L54

 Just look at the line highlighted and ignore the rest. :smile:

* The .json config file to appdmg on the command line: https://gist.github.com/justinclift/4bc95032530439edb05c44a807723441

* The artwork (just in case it's useful, which it probably isn't): https://github.com/sqlitebrowser/art-assets/tree/master/osx_install_backgrounds

You can probably just update the values in the with "Syncthing.app", your own background image (and the 2X), and the X,Y positions and call it a day. :smile:

**Comment by xor-gate** [comment]
Thanks @justinclift as I have the dmg-building in-place and not a big fan of node-js utiltity scripts. I probably have solved the problem. During staging before creating the DMG the copy didn't preserved the symlinks. Now I have created a new release which should fix it:

https://github.com/xor-gate/syncthing-macosx/releases/download/v0.14.5/Syncthing-0.14.5-testing.dmg

I have done this fix: https://github.com/xor-gate/syncthing-macosx/commit/e41767958917d3dce0bb61e1edfe8d25fd90ef3a

**Comment by justinclift** [comment]
Yep, that seems to have fixed it. :smile:

```
$ codesign --verify --verbose --deep Syncthing.app
Syncthing.app: valid on disk
Syncthing.app: satisfies its Designated Requirement
```

**Comment by xor-gate** [comment]
That's awesome! Thank you for your help and testing.

**Comment by xor-gate** [comment]
I have silently removed the "broken" dmg in the release and replaced with the fixed one. Also the `-testing` and zipfile have been removed. Otherwise this would confuse new users.

**Comment by justinclift** [comment]
You're welcome. :smile:

**Comment by xor-gate** [comment]
I'm closing this, when there are any problems. Don't hesitate to open a new issue (or continue in this one if there are still problems).

**Comment by jipzingking** [comment]
Please sign the the app bundle in release key rather the developer key to make gatekeeper happy.

Now the app is signed with the developer key:

Executable=/Volumes/Syncthing/Syncthing.app/Contents/MacOS/Syncthing
Identifier=com.github.xor-gate.syncthing-macosx
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=932 flags=0x0(none) hashes=23+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=0f2a975e438011471df9586fdd098cf5b63cece7
CandidateCDHash sha256=8f70bef4824f1922726e5ebec220ee24fdb7ae21
Hash choices=sha1,sha256
CDHash=8f70bef4824f1922726e5ebec220ee24fdb7ae21
Signature size=4696
Authority=**_Mac Developer_**: jerryjacobs1989@gmail.com (TT7GM4W59N)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=9 Aug 2016, 6:42:36 PM
Info.plist entries=29
TeamIdentifier=C24U83K674
Sealed Resources version=2 rules=12 files=30
Internal requirements count=1 size=208

And gatekeeper prevent me to open it directly even though it is signed correctly. It will make us more convenient if you could sign it in release key.

**Comment by xor-gate** [comment]
You should allow from gatekeeper `Mac App Store and identified developers`: 

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html#//apple_ref/doc/uid/TP40012582-CH12-SW2

**Comment by jipzingking** [comment]
I have already allow gatekeeper from Mac App Store and identified developers. However, 

➜  /Applications codesign -dvv Google\ Chrome.app 
Executable=/Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Identifier=com.google.Chrome
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=273 flags=0x800(restrict) hashes=3+3 location=embedded
Signature size=8896
Authority=Developer ID Application: Google Inc.
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=8 Nov 2016, 11:19:50 AM
Info.plist entries=34
TeamIdentifier=EQHXZ8M8AV
Sealed Resources version=2 rules=7 files=191
Internal requirements count=1 size=132
➜  /Applications codesign -dvv Syncthing.app 
Executable=/Applications/Syncthing.app/Contents/MacOS/Syncthing
Identifier=com.github.xor-gate.syncthing-macosx
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=1060 flags=0x0(none) hashes=27+3 location=embedded
Signature size=4696
Authority=Mac Developer: jerryjacobs1989@gmail.com (TT7GM4W59N)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=16 Oct 2016, 11:06:46 PM
Info.plist entries=30
TeamIdentifier=C24U83K674
Sealed Resources version=2 rules=13 files=35
Internal requirements count=1 size=208

The difference is that Google Chrome is signed by certificate type of Developer ID Application but Syncthing is signed by certificate type of Mac Development.

From [https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html) Table 14-2, Mac Development is used to enable certain app services for a Mac app during development and testing. And it would not pass gatekeeper.

Thus, if you could sign application with certificate of Developer ID Application, it will be easier for us to use the application.

Thanks.

**Comment by xor-gate** [comment]
I will investigate ASAP (no hard due date).

**Comment by justinclift** [comment]
Ahhh yeah, I remember having to do this too.  The docs for this are way more complicated than they need to be, which was off-putting.

@xor-gate If you have 5 mins, it's actually pretty simple to do. :smile:

1. Goto https://developer.apple.com, login there.

2. On the "Account" page (once logged in) there is a vertical menu on the left.  Choose "Certificates, IDs & Profiles" (2nd option from the top).

3. At the top of the vertical menu on this page, there is a drop down selector with options.  Change it to the "OSX" option.  Now you'll be in the "Mac Certificates" section.

4. Click the **+** symbol on the right:

 ![screenshot_2016-11-10_13-24-47](https://cloud.githubusercontent.com/assets/406299/20178806/d36409a8-a74a-11e6-9450-9421ef1a5868.png)

5. Choose "Developer ID", then click continue:

 ![screenshot_2016-11-10_13-32-16](https://cloud.githubusercontent.com/assets/406299/20178831/ed7553f6-a74a-11e6-8b2e-259cfdec092d.png)

6. Choose "Developer ID Application", then click continue:

 ![screenshot_2016-11-10_13-35-06](https://cloud.githubusercontent.com/assets/406299/20178867/14101bf4-a74b-11e6-9ae0-cba3d5cf2efa.png)

7. That's the selection steps done to get you to the right part.  Now just follow the instructions it gives (open Keychain Access utility on your Mac, generate the request (CSR), download your certificate).

That's how I did it anyway.

Hope that helps. :smile:

**Comment by xor-gate** [comment]
Nope, it doesn't show up. I need to pay the 99 bucks to make it work -> Enable Developer ID.

<img width="1078" alt="screen shot 2016-11-10 at 19 30 00" src="https://cloud.githubusercontent.com/assets/1050166/20189142/1fca288c-a77c-11e6-8b3c-6169ce1ca530.png">

**Comment by xor-gate** [comment]
Under XCode it looks like this:

**target build settings**
<img width="770" alt="screen shot 2016-11-10 at 19 47 24" src="https://cloud.githubusercontent.com/assets/1050166/20189684/9db51728-a77e-11e6-99ac-c393307fe0f2.png">

**preferences -> account**
<img width="761" alt="screen shot 2016-11-10 at 19 47 44" src="https://cloud.githubusercontent.com/assets/1050166/20189687/a29557a8-a77e-11e6-95fb-e467d169f798.png">

**Comment by xor-gate** [comment]
Last resort: https://support.apple.com/kb/ph18657?locale=en_US

**Comment by justinclift** [comment]
Ahhhh yeah.  Forgot about the $99 thing. Oops. :wink:

**Comment by xor-gate** [comment]
I will add a note in the README about this, as I'm not going to spend the $99 any time soon.

**Comment by xor-gate** [comment]
As @virusman is now a project contributor he signed the latest [v0.14.33-1](https://github.com/xor-gate/syncthing-macosx/releases/tag/v0.14.33-1) release with his keys.

**Comment by ssbarnea** [comment]
I am more than willing to donate some small amount to have a signed app on MacOS and I am sure others would be willing to. Without signing syncthing future would be kinda doomed as MacOS platform cannot be ignored.

PS. I know that I can build my own, but my life if too short to do that with all my tools, I would rather forget about the one that is not easy to install/use ;)

**Comment by xor-gate** [comment]
@ssbarnea [last version](https://github.com/xor-gate/syncthing-macosx/releases/tag/v0.14.33-1) is signed by @virusman developer account and should work without problems
