### ISSUE TITLE
Use with already installed syncthing

### ISSUE THREAD

**Issue by krisak** [xor-gate/syncthing-macosx#9]
From what i undestand this tray app is also spawning its own syncthing instance. Is it possible to run it with homebrewed version?

Or what is the advantage of including syncthing in the app?

**Comment by xor-gate** [comment]
Most mac users are not developers, they need a drag-and-drop application which runs out of the box without a handful of commands to type in and file to download and copy. `syncthing-macosx` ships as a complete package compared to others. 

I agree power users should be able to disable running the executable from the App Bundle. It would need some GUI addition to enable/disable and select an custom executable.

I have no time when I will add this. Maybe you could try to set a dummy executable (`/bin/true` for now with:

```
defaults write com.github.xor-gate.syncthing-macosx Executable /bin/true
```

See https://github.com/xor-gate/syncthing-macosx#configuration-and-defaults

**Comment by krisak** [comment]
Sorry i didnt want to be mean or anything. I was just asking. I actualy dont mind that much and what the hell i can switch to this one. It was just not very clear for me, because from first read through it seemd like its just gui that calls the api not the whole syncthing app. I actualy installed homebrewed syncthing version after reading this app, because i thought i need syncthing already instaled for this to work.

**Comment by xor-gate** [comment]
My bad, you are 100% right, the behaviour is not clearly documented. I really appreciate your feedback and I didn't read the issue in a fashion it was mean to me.

In the upcoming time I will document the executable is started and add a option in the GUI for people who like to run their own instance (even remote controlled).

I will keep this issue open as long as I have not fixed it. This way you can also track progress.

**Comment by krisak** [comment]
Well i missed it. Its there:
- Ships syncthing binary
It just might be in the first description or atleast on first place of the list. Also if this is ment to be very user friendly, i guess "syncthing binary" wont make much sense to non technical users.

Maybe just say something like: "Full package syncthing app. Tray app with syncthing running in background." I realy dont know. Just trying to be helpful. Great work btw :)

**Comment by xor-gate** [comment]
You are right about that one, the time when I started with syncthing (few years ago) it was mostly used by "power-users". And because my drag-and-drop solution is user-friendly and doesn't need special knowledge I should document it more to end-users. And it is more often downloaded (with builtin update-checker for the bundle).

**Comment by xor-gate** [comment]
I'm closing this in favor of "feature issue" #14. Thanks for reporting!
