### ISSUE TITLE
Should be able to see console somewhere

### ISSUE THREAD

**Issue by calmh** [xor-gate/syncthing-macosx#91]
I started Syncthing-macos today, and noticed it flipped between "running" / "unavailable" with syncthing apparently not able to start correctly. There is no real way to figure out what's going on in this situation.

(In the end it turned out I had a very old syncthing in ~/library/application support/syncthing-macos and Syncthing's downgrade protection prevented it from starting up. Removing it resolved the problem.)

**Comment by xor-gate** [comment]
🤕 just like SyncTrayzor we should indeed have stdout and stderr routed to a view.

**Comment by ttimasdf** [comment]
+1, at least output to a log file somewhere else.

**Comment by xor-gate** [comment]
As [discussed on the forum](https://forum.syncthing.net/t/sync-regularly-fails-with-temp-files/16156/7?u=jerryjacobs) we should set `-logfile="default"`.

**Comment by xor-gate** [comment]
Fixed in v1.13.1-1 release, we now write it with the `-logfile=default` parameter.
