### ISSUE TITLE
Always use bundled Syncthing binary

### ISSUE THREAD

**Issue by calmh** [xor-gate/syncthing-macosx#93]
Apparently special permissions like "full disk access" (required in Mojave to read some stuff under ~/Library etc) only take effect for things running from within a (signed) app bundle in /Applications. This means that for Syncthing to get such access, it must run from there. To enable that, Syncthing-macOS could/should always use the bundled Syncthing binary.

As far as I know there is no downside to this, other than requiring more frequent release updates. The bundled Syncthing should be compiled without auto-update capabilities. (More frequent releases could be facilitated by automation, and the knowledge that any Syncthing release happens on the first Tuesday of the month, modulo sudden emergency fuckup rescues.)

We can imagine it being possible to override the bundled Syncthing in some way like it is currently. Either by explicit config or just "if it exists in ~/Library/... then use that one instead".

**Comment by mstgrv** [comment]
Was only just getting around to posting this here, and it's already been posted - thanks very much @calmh!

This relates to a forum post I made here: https://forum.syncthing.net/t/syncing-mobilesync-folder-on-macos-syncthing-cant-sync-anymore-in-mojave/12740/7
