### ISSUE TITLE
Use with syncthing v1.1?

### ISSUE THREAD

**Issue by iliyang** [xor-gate/syncthing-macosx#96]
I understand the syncthing-macos doc says that the bundle should not be used alongside any other syncthing instances. Unfortunately the bundle comes with only syncthing v1.0. Can I expect the bundle to still work if I replace the syncthing binaries inside it with v1.1?

**Comment by xor-gate** [comment]
The syncthing instance auto-updates itself for the current version, and should work just fine 👍

**Comment by xor-gate** [comment]
I just checked, my install of the bundle has autoupdated to 1.1 and works like a charm. So no problems.

**Comment by iliyang** [comment]
Oh, this is great, thanks guys!!
